import json
R = {
 "row": "L",
 "environment": {
  "encrypted": True,
  "seed": "scripts/ui_clickthrough_seed.py default (STATE C, 453 articles) into an ENCRYPTED store (OO_DB_PASSPHRASE set, OO_DB_PLAINTEXT unset); then /tmp/claude-0/walk/L/seed_extra.py with the server stopped and the same passphrase: SYNTHETIC World Bank figures (NY.GDP.MKTP.CD, SP.POP.TOTL, SP.DYN.LE00.IN x 44 countries incl. XKX + 6 WB aggregates WLD/HIC/EUU/EAS/LIC/SSF x 2019-2023) through src.stats.sdmx.parse_worldbank + store_figures, 6 USGS MCS supply rows through parse_mcs_csv, 4 index series (CommodityPrice), 3 law documents (fr/uk/eu) with revisions, Wikipedia-lane change rows (adapted from docs/audit/living-sources-clickthrough-2026-09-25/seed.py). Boot autoseed added the 6,418-source catalogue; L1 'Re-seed catalog' added 205 sources / 23 laws.",
  "ports": [8822],
  "scratch_dir": "/tmp/claude-0/walk/L",
  "notes": "Launched only with the open-omniscience console script (proxy vars unset), booted LOCKED with neither OO_DB_PASSPHRASE nor OO_DB_PLAINTEXT; unlocked in Chromium via #pw/#btn-unlock. Both open_omniscience.db and wiki.db are ciphertext at rest (first bytes are not the SQLite header). Airplane mode stayed engaged throughout; the only consent popup opened (L11 'Load standard country data') was cancelled with 'Stay offline' and /api/system/network then read online:false; the net-coach was answered 'Not now'. Chromium 1194 headless via Playwright sync API; main pass 1440x950, phone pass 375x800. Map-shape tooltips are native SVG <title> children: their text was read from the element after a real mouse hover (headless Chromium does not paint native tooltips); #oo-tip bubble text was read from the live bubble after a real hover. Governments and Markets data are SYNTHETIC values pushed through the app's own parsers, so the renderers were exercised but the gate's 'walked with REAL data' clause is still not met. Server log: one startup WARNING 'could not seed the source catalog at startup' (IntegrityError UNIQUE sources.domain in seed_legal_sources) in the same second as the walk's own 'Re-seed catalog' press, i.e. a race between the deferred startup seed and the manual re-seed; no visible effect. Only port 8822 used (8823 unused); server PID 29074 killed at the end. 20 key screenshots in the scratch dir, the rest in extra/; raw per-step observations in res-*.json; exported CSV and bulletin text saved beside them."
 },
 "steps": [
  {"id": "L1", "result": "pass", "locales": ["en"], "screenshot": "L1-tip-EUU-en.png",
   "observed": "Governments > Law. Legal changes: bold codes GBR, EUU, FRA, each dotted-underlined with #oo-tip 'United Kingdom' / 'European Union — not an ISO code' / 'France'. 'Re-seed catalog' toast: 'Seeded 205 sources, 23 laws.' Tracked laws: 27 rows, every Jurisdiction cell 3 uppercase letters from {CAN, DEU, EUU, FRA, GBR, INT, TLS, USA}; no lowercase uk/eu/int/de. Hovers: GBR 'United Kingdom' (stored as uk and as gb), DEU 'Germany', EUU 'European Union — not an ISO code', INT 'International — not an ISO code', FRA 'France', CAN 'Canada', USA 'United States' (no tail on real countries). TLS (Timor-Leste, from legal_sources_generated.yml) is outside the brief's listed set but is a correct alpha-3 with hover 'Timor-Leste'."},
  {"id": "L2", "result": "fail", "locales": ["en"], "screenshot": "L2-directory-AX-tip-en.png",
   "observed": "PASS parts: Agenda Country dropdown = 'all' + 32 entries '🇦🇷 Argentina (ARG)', '🇦🇺 Australia (AUS)', '🇧🇪 Belgium (BEL)', '🇧🇷 Brazil (BRA)'…, ordered by name (Intl.Collator check clean), every code 3 uppercase letters, '🇪🇺 European Union (EUU)', only '🌐 International (INT)' has the globe. Picking France: 'showing 3 of 153' (FRA pills); back to all: 153 of 153. List + Group by country: headings are codes with dotted underline + hover (INT 75 → 'International — not an ISO code', CHN 'China', …) and a 'No country 2' group; event pills are codes with a 4px corner dot (::after), no INT pill. Calendar directory: '· holidays · AFG' hover 'Afghanistan'. FAIL part: the directory also shows real ISO territories as bare TWO-letter codes 'AX', 'AI', 'BQ', 'BV', 'IO' ('· holidays · AX'), whose hover reads 'not a recognised country code' (Åland, Anguilla, Bonaire, Bouvet, British Indian Ocean Territory)."},
  {"id": "L3", "result": "fail", "locales": ["en"], "screenshot": "L3-country-filter-closed-en.png",
   "observed": "Manage sources table: Country column ISR/FRA/UGA… with hovers Israel/France…; Lang column eng/fra/spa/tel with hovers English/French/Spanish/Telugu. Country filter: 209 entries 'Afghanistan (AFG) ·4' …, ordered by name (collator clean) — BUT three entries print a lowercase alpha-2: 'Anguilla (ai) ·1', 'Cook Islands (ck) ·1', 'Vatican City (va) ·2'. Language filter: 79 entries 'English (eng) ·2954', 'Spanish (spa)', 'French (fra)'…. Ticking France leaves only FRA rows (130 sources). Closed filter label reads 'fr' (not FRA / France (FRA)); with English ticked the language filter reads 'en' — predicted finding confirmed. Clear restores 6418 and 'Any'/'Any'. Statistics producers: international producers show '—', national ones codes with hover (RUS 'Russia', FRA, GBR, DEU…). No 'pcm'-style language exists in this corpus (not measurable)."},
  {"id": "L4", "result": "pass", "locales": ["en"], "screenshot": "",
   "observed": "'Export all (CSV)' produced a browser download 'open-omniscience-sources.csv' (6,418 rows, saved in the scratch dir). Header: name,…,reliability_score,country_iso3 — contains 'country' and 'country_iso3', the latter last. fr→FRA, de→DEU; 1,458 rows have both cells empty; 0 rows with an empty country and a filled iso3; no stored country maps to two different iso3 values. Rows 'va' (2), 'ck' (1), 'ai' (1) export an EMPTY country_iso3 although these are real ISO 3166-1 codes (VAT/COK/AIA) — the table gap in the defects, not a refusal to guess an unreadable code. Hint text still says 'Country is a 2-letter code.' and its column list omits country_iso3: judged stale (P3 finding), since imports accept 2 letters, 3 letters or a name."},
  {"id": "L5", "result": "fail", "locales": ["en"], "screenshot": "L5-first-row-tip-en.png",
   "observed": "Map: 229 shapes; tooltips give NAME + count ('France — 56 articles', 'Germany — 56 articles'). Table: 210 country cells, all with a hover; FIRST row '(none)' (1458 sources with no country) hovers 'not a recognised country code' — finding (1) CONFIRMED. Rows 'va', 'ai', 'ck' are lowercase alpha-2 with the same 'not a recognised' hover. 'Not covered (43)' pills mix codes (ASM 'American Samoa', ABW 'Aruba') with lowercase alpha-2 (aq, ax, bl, bq, bv, cc, cx, eh, fk, gf, gg, gp, gs, hm, io, je, mf, mq, ms, nf, nu, pm, pn, re, …) all hovering 'not a recognised country code'. 'Top country: United States — 239 sources, 4.9% of located within the 12% guard …' — English name, no code, and the line stays English in fr/ar — finding (2) CONFIRMED. Filter box: 'DEU' → 'No matching countries.'; 'germ' finds DEU; 'de' matches tag substrings — finding (3) CONFIRMED. Clicking FRA jumps to Settings > Advanced > Sources: table shows only FRA rows (130 source(s)) but the Country filter reads 'Any' with NOTHING ticked (re-checked for 8 s; see defects)."},
  {"id": "L6", "result": "pass", "locales": ["en", "fr", "ar", "zh"], "screenshot": "L6-DEU-tip-ar.png",
   "observed": "Bare language switch from the top-bar menu with the coverage table open, no reload: DEU hover 'Allemagne' / 'ألمانيا' / '德国' / 'Germany'; map tooltips follow ('Allemagne — 56 articles', 'ألمانيا — 56 مقالة', '德国 — 56 篇文章', 'Germany — 56 articles'); ar sets dir=rtl and the cell still reads Latin 'DEU'. The 2026-09-16 frozen-language fix holds on this panel."},
  {"id": "L7", "result": "fail", "locales": ["en"], "screenshot": "L7-coverage-detail-DEU-en.png",
   "observed": "Coverage lens: shape tooltips give name + value ('France — 130 sources', 'Germany — 60 sources'). No territory with data is drawn as a point in this corpus, so the dot-tooltip prediction is not measurable here. Clicking Germany opens a panel headed 'DEU' (Europe, Sources 60, Articles 56, Keyword mentions 3 598) and the heading carries NO title/hover — the name is only in the map tooltip; judged not to meet 'the name in the hover' (P3). Stories lens: 34 dots; detail line 'Aug 17, 2027 · Jakarta (IDN) · -6.21, 106.85 · agenda', IDN hover 'Indonesia' (pass)."},
  {"id": "L8", "result": "fail", "locales": ["en"], "screenshot": "L8-insights-by-country-en.png",
   "observed": "Insights > Map, window 3650 + Refresh: 'By country' first column prints stored lowercase alpha-2 'br, cn, de, eg, es, fr, gb, mx, pt, ru, sa, us' with no hover — finding (a) CONFIRMED. 'By city': 'No data — index the corpus (sources need a country/city).' (seed sources have no city; not measurable). Super-groups > Cross-country map of 'voting': Country table SAU/FRA/ESP/CHN/BRA/USA/GBR with hovers (SAU 'Saudi Arabia'); but 'Languages: ar · en · es · pt · zh' and 'By language: es 84 · en 47 · pt 28 · ar 28' and the group chips '(ar/bn/de/en/…)' print ISO 639-1, not 639-2/T — Q306 display finding (g) CONFIRMED."},
  {"id": "L9", "result": "pass", "locales": ["en"], "screenshot": "L9-living-law-EUU-en.png",
   "observed": "Settings > Wikipedia > Edition (#wiki-lang) is a <select>, 147 options, 0 optgroups, flat, native name first: '中文 — Chinese (zh)', 'English — English (en)', 'Français — French (fr)', 'Deutsch — German (de)'. Living sources > Wikipedia rows carry pills 'fra' (hover 'French') and 'eng' ('English'); > Law rows carry pills GBR 'United Kingdom', EUU 'European Union — not an ISO code', FRA 'France'; pills show the 4px corner dot, no underline."},
  {"id": "L10", "result": "fail", "locales": ["en"], "screenshot": "L10-minerals-supply-en.png",
   "observed": "SYNTHETIC data. Indices: 'All' and 'Europe' boards labelled by index names only ('France — share prices', 'Germany — share prices', 'United Kingdom — share prices', 'S&P 500'); no country code and no country hover anywhere (only currency codes EUR/GBP/USD). Verdict: names-in-prose inside an index name are acceptable (it is the index's own name, not a country cell). Minerals supply (USGS rows via parse_mcs_csv): Area column prints 'US', 'AU', 'CN', 'US', 'WLD', 'WLD' raw with no hover — finding (l) CONFIRMED. Feed table grey lines name producers ('EIA/FRED', 'world-bank'), not countries."},
  {"id": "L11", "result": "fail", "locales": ["en"], "screenshot": "L11-statistics-level-table-en.png",
   "observed": "SYNTHETIC World Bank figures via parse_worldbank/store_figures (the online load itself is not measurable). Consent popup for 'Load standard country data': 'This action needs the network:' followed by NOTHING (side note confirmed); cancelled with 'Stay offline', online stays false. Countries / Compare pickers: 44 entries 'Afghanistan (AFG)', 'Albania (ALB)', … name order, no alpha-2. Map (Population): 'France — FRA · France: 72M', 'Kosovo — XKX · Kosovo: 1.9M' (no 'not an ISO code' disclosure for XKX); clicking Germany switches to Countries with 'Germany (DEU)'. Groups > Computed > Europe: 'Range across reporting members (23): 1.9M (XKX) to 88M (DEU)' (codes, no per-code hover); 'missing: AND, ax, BIH, BGR, BLR, EST, FRO, gg …' mixes alpha-3 with lowercase ax/gg/je; each strategy's refusal text prints stored alpha-2 '(ad, ax, ba, bg, by, ee, fo, gg…)'. Statistics (NY.GDP.MKTP.CD, level): ranked 'Area' table WLD, HIC, EAS, USA, EUU, CHN…; WLD/HIC/EAS hover 'not a recognised country code', EUU 'European Union — not an ISO code', countries named; no aggregate gets a country name or flag. Placeholders still 'FR or all' and 'FR'."},
  {"id": "L12", "result": "fail", "locales": ["en"], "screenshot": "L12-bulletin-doc-en.png",
   "observed": "Advanced > Uninstall & wipe > Bulletin (nested, as recorded). Yearly draft built ('Draft built.'), opened in a new tab: 'Source countries: RUS 21, CHN 20, FRA 16, DEU 14, USA 11, SAU 10, BRA 9, MEX 9, EGY 8, PRT 8, GBR 7, ESP 5; 2 from sources with no country recorded.'; 'Languages: eng 23, rus 20, zho 20, ara 18, por 17, fra 15, spa 14, deu 13.'; By country headings 'Russia (RUS) · Europe', 'France (FRA) · Europe' …. BUT the document also carries the law-change card 'Law changed (fr): Walk Code civil (extract)' and 'Measured: … jurisdiction fr …' — a lowercase alpha-2 country code, which the step's 'no lowercase two-letter country code anywhere' forbids. Edition deleted afterwards ('No editions yet.')."},
  {"id": "L13", "result": "pass", "locales": ["fr", "ar", "zh"], "screenshot": "L13-src-country-filter-ar.png",
   "observed": "Pre-reload glance: after a bare switch to fr/ar/zh the Law hovers still read 'United Kingdom' / 'Germany' / 'European Union — not an ISO code' (frozen-language note). After RELOAD: fr GBR 'Royaume-Uni', DEU 'Allemagne', EUU 'Union européenne — pas un code ISO', INT 'International — pas un code ISO'; Agenda starts 'tout', '🇿🇦 Afrique du Sud (ZAF)', '🇩🇪 Allemagne (DEU)'; Sources filter 'Afghanistan (AFG)', 'Afrique du Sud (ZAF)'…, language 'anglais (eng)', 'français (fra)'. ar: dir=rtl, CAN 'كندا', EUU 'الاتحاد الأوروبي — ليس رمزًا من رموز أيزو', INT 'دولي — ليس رمزًا من رموز أيزو'; filter 'أرمينيا (ARM) ·8' renders with proper parentheses (screenshot), codes Latin/unreversed. zh: DEU '德国', EUU '欧盟 — 非 ISO 代码', INT '国际 — 非 ISO 代码', filter '阿根廷 (ARG)'. Sort order matched Intl.Collator in every locale; on-screen codes identical across locales. Governments map titles localised ('Allemagne — DEU · Allemagne: 88M', 'ألمانيا — DEU …', '德国 — DEU …'). Same-root leftovers seen in every locale: 'Anguilla (ai)' in the country filter; Home law card 'Law changed (fr): …' stays English."},
  {"id": "L375", "result": "fail", "locales": ["en"], "screenshot": "L375-sources-filters-closed-en.png",
   "observed": "375x800 en: document scrollWidth - clientWidth = 0 on Law, Agenda list, Library coverage, Governments map and countries, and Settings > Advanced > Sources (wide tables scroll inside their own overflow:auto boxes; EUU hover works at 375). BUT the Manage sources filter row collapses: Search box 25 px wide, Language/Country/Type/Tags controls overlap (x=71/95/118/142, each 90 px wide), labels print on top of each other ('LanguCountrTypeTags'), and a click on the Country filter is intercepted by the neighbouring control, so the Country filter cannot be opened at phone width."}
 ],
 "page_errors": [],
 "http_errors": [],
 "junk_text": [
  "Insights > Super-groups > Cross-country map (method text): '… Unlocated sources are bucketed as null, not dropped. …' — developer wording, not a rendering bug",
  "Commodities > Minerals supply caveat: 'A None value is a published gap.' — Python 'None' in user text",
  "Governments > Groups > Computed refusal text: 'Re-request with allow_incomplete to compute it anyway' — API parameter name in user text"
 ],
 "defects": [
  {"title": "28 real ISO 3166-1 codes (incl. Vatican City) are missing from the alpha-3 table, so they show as two-letter codes hovering 'not a recognised country code'",
   "severity": "P2", "step_ids": ["L2", "L3", "L4", "L5", "L11", "L13"],
   "repro": "Encrypted seed + boot autoseed; Settings > Advanced > Calendar directory (rows '· holidays · AX'/'AI'/'BQ'/'BV'/'IO'); Settings > Advanced > Sources > Country filter ('Anguilla (ai)', 'Cook Islands (ck)', 'Vatican City (va)'); Library > World coverage table rows va/ai/ck and 'Not covered (43)' pills; Governments > Groups > Computed > Europe 'missing: … ax … gg …'; Export all (CSV) rows va/ck/ai.",
   "expected": "Every code the user sees is alpha-3 with the localised name in the hover (VAT 'Vatican City', ALA 'Åland Islands', AIA 'Anguilla' …); the export's country_iso3 filled for real ISO codes.",
   "actual": "Bare 'va', 'ai', 'ck', 'aq', 'ax', 'bl', 'bq', 'bv', 'cc', 'cx', 'eh', 'fk', 'gf', 'gg', 'gp', 'gs', 'hm', 'io', 'je', 'mf', 'mq', 'ms', 'nf', 'nu', 'pm', 'pn', 're', … (uppercase in the calendar directory), hover 'not a recognised country code', CSV country_iso3 empty for va/ck/ai.",
   "evidence": "L2-directory-AX-tip-en.png, L13-src-country-filter-ar.png, extra/L5-coverage-map-en.png, res-L3.json/res-L5.json. Cause: src/catalog/countries.py:614-640 _ISO3_TO_2_TEXT (mirrored verbatim at src/static/app-core.js:64-81) lists only World Bank economies + a few territories; configs store ai ax bl bq bv cc ck cx eh fk gf gg gp hm io je mf mq ms nf pm re sh sj tk va wf yt, none of which resolve; ooCountryCode (app-core.js:141-154) then returns the raw value and ooCountryTitle the 'not a recognised' line."},
  {"title": "Insights > Map 'By country' table prints stored lowercase alpha-2 with no hover",
   "severity": "P2", "step_ids": ["L8"],
   "repro": "Insights > Map, Window 3650, Refresh; read the 'By country' first column.",
   "expected": "Three-letter uppercase codes (BRA, CHN, DEU…) each with the localised name in the hover.",
   "actual": "'br', 'cn', 'de', 'eg', 'es', 'fr', 'gb', 'mx', 'pt', 'ru', 'sa', 'us', plain <strong>, no title.",
   "evidence": "L8-insights-by-country-en.png; src/analytics/queries.py:3193-3197 emits {code: stored alpha-2}; src/static/app-map.js:1676 prints esc(a.code||a.name) raw (ooCountryCell only for city rows)."},
  {"title": "World coverage → Sources jump: table filtered to FRA but the Country filter shows 'Any' with nothing ticked",
   "severity": "P2", "step_ids": ["L5"],
   "repro": "Fresh page, Library > World coverage, click the FRA code in the table.",
   "expected": "Settings > Advanced > Sources opens with the Country filter pre-ticked (France) and its label naming it, matching the filtered table.",
   "actual": "Table shows '130 source(s)', FRA rows only, while the Country filter reads 'Any' and no checkbox is ticked (observed for 8 s and after opening the filter). The visible filter state misstates what is displayed; ticking another country would silently drop FRA.",
   "evidence": "L5-click-FRA-sources-state-en.png, res-L5b.json. Likely race: openSourcesForKeyword (src/static/app-sources.js:579-590) ticks after its own loadSrcFacets(), then showTab('sources') → _openAdvanced('sources') (app-shell.js:109-111, 512-518) fires the section's toggle loader (app-shell.js:478) which runs loadSrcFacets() again and re-renders the list unticked + summary 'Any'."},
  {"title": "Sources Manage-sources filter row collapses at 375 px; Country filter cannot be opened",
   "severity": "P2", "step_ids": ["L375"],
   "repro": "Viewport 375x800, Settings > Advanced > Sources; try to click the Country filter.",
   "expected": "Filters wrap to their own lines, labels readable, each control clickable.",
   "actual": "Search 25 px wide; Language/Country/Type/Tags overlap (x=71/95/118/142, 90 px each); labels overprint ('LanguCountrTypeTags'); click on Country is intercepted by the next control. No page-level horizontal scroll.",
   "evidence": "L375-sources-filters-closed-en.png, res-L375.json; markup src/static/index.html:2498-2515 (.row with flex children)."},
  {"title": "'Load standard country data' consent popup names no action",
   "severity": "P2", "step_ids": ["L11"],
   "repro": "Governments > Countries > 'Load standard country data' (then 'Stay offline').",
   "expected": "Invariant #14: the ONE consent popup names the action ('This action needs the network: <action>').",
   "actual": "'This action needs the network:' followed by an empty #net-consent-reason. Consent is still required (not a breach); the disclosure is missing. Outside row L.",
   "evidence": "L11-consent-load-standard-en.png; src/static/app-gov-law.js:599-601 calls ensureOnline() with no reason."},
  {"title": "Law-change briefing card prints the stored lowercase jurisdiction, on Home and in the bulletin",
   "severity": "P3", "step_ids": ["L12", "L13"],
   "repro": "With a flagged law revision (jurisdiction fr): Home briefing card; or Advanced > Bulletin > Yearly > Build a draft > Open.",
   "expected": "'Law changed (FRA): …' (hover name on screen; name + code in print); no lowercase two-letter code in the bulletin.",
   "actual": "'Law changed (fr): Walk Code civil (extract)' and 'Measured: … jurisdiction fr …', in English even in fr/ar/zh.",
   "evidence": "L13-home-law-card-fr.png, bulletin-doc.txt:254-258; src/briefing/producers.py:1468 title=f\"Law changed ({doc.jurisdiction}): …\"."},
  {"title": "Sources closed filter label prints the stored value ('fr', 'en')",
   "severity": "P3", "step_ids": ["L3"],
   "repro": "Settings > Advanced > Sources: tick France only, close the Country filter; tick English only, close Language.",
   "expected": "'FRA' or 'France (FRA)'; 'eng' or 'English (eng)'.",
   "actual": "'fr' and 'en'.",
   "evidence": "L3-country-filter-closed-en.png; src/static/app-sources.js:317-322 (updateMselSummary prints v[0])."},
  {"title": "Governments > Groups computed refusal text lists members as stored lowercase alpha-2",
   "severity": "P3", "step_ids": ["L11"],
   "repro": "Governments > Groups > Computed from members > Group 'Europe', Indicator population.",
   "expected": "Member codes in alpha-3, like the 'missing:' line and the Range line beside it.",
   "actual": "Each strategy: '29 of 52 members did not report this indicator for this period (ad, ax, ba, bg, by, ee, fo, gg…)'; English-only; exposes 'allow_incomplete'.",
   "evidence": "extra/L11-groups-computed-europe-en.png, res-L11b.json; src/stats/aggregate.py:197-205 joins missing_value raw."},
  {"title": "Commodities > Minerals supply Area column prints USGS codes raw with no hover",
   "severity": "P3", "step_ids": ["L10"],
   "repro": "With USGS MCS figures stored: Commodities > Minerals supply.",
   "expected": "USA/AUS/CHN with name hovers; WLD as a disclosed aggregate.",
   "actual": "'US', 'AU', 'CN', 'WLD' as plain text, no title.",
   "evidence": "L10-minerals-supply-en.png; src/static/app-markets.js:488 esc(r.ref_area)."},
  {"title": "Concept map and group chips show ISO 639-1 language codes, not 639-2/T",
   "severity": "P3", "step_ids": ["L8"],
   "repro": "Insights > Super-groups > Elections & democracy > voting.",
   "expected": "Q306 display: 'ara · eng · spa …' with language-name hovers.",
   "actual": "'Languages: ar · en · es · pt · zh', 'By language: es 84 · en 47 …', chips '(ar/bn/de/en/…)'.",
   "evidence": "L8-concept-map-en.png; src/static/app-insights.js:385-386, 493-501."},
  {"title": "World coverage: '(none)' row hovers 'not a recognised country code'; filter cannot find the on-screen code; 'Top country' shows an English name only",
   "severity": "P3", "step_ids": ["L5"],
   "repro": "Library > World coverage: hover the first row; type DEU into the filter; read 'Top country:' in fr/ar.",
   "expected": "Absent country labelled as absent (not as unreadable); DEU finds Germany; Top country shows the code with the localised name in the hover.",
   "actual": "'(none)' → 'not a recognised country code'; DEU → 'No matching countries.'; 'Top country: United States — 239 sources, 4.9% of located within the 12% guard …' in English in every locale.",
   "evidence": "L5-first-row-tip-en.png, L5-filter-DEU-en.png, L6-DEU-tip-ar.png; src/analytics/source_country_rollup.py:73,85; src/static/app-sources.js:190-195, 203-206."},
  {"title": "World map Coverage detail heading shows the code with no hover",
   "severity": "P3", "step_ids": ["L7"],
   "repro": "World map > Coverage, click Germany.",
   "expected": "Heading 'DEU' with the localised name in the hover (Q302 pair, as the comment claims).",
   "actual": "<strong>DEU</strong> with no title.",
   "evidence": "L7-coverage-detail-DEU-en.png; src/static/app-map.js:1435-1442."},
  {"title": "Non-ISO disclosure missing or mislabelled on Governments surfaces (XKX, WB aggregates)",
   "severity": "P3", "step_ids": ["L11"],
   "repro": "Governments > Map (Population) hover Kosovo; Statistics > NY.GDP.MKTP.CD level map, hover WLD/HIC/EAS.",
   "expected": "Q303: XKX disclosed as 'not an ISO code'; a producer aggregate described as an aggregate, not as an unreadable code.",
   "actual": "'Kosovo — XKX · Kosovo: 1.9M' (no disclosure); WLD/HIC/EAS hover 'not a recognised country code'.",
   "evidence": "L11-statistics-level-table-en.png, res-L11.json; src/static/app-gov-law.js:587 valueLabel uses ooCountryName not ooCountryTitle; src/static/app-core.js:188-191."},
  {"title": "Stale on-screen hints still teach two-letter codes",
   "severity": "P3", "step_ids": ["L4", "L11"],
   "repro": "Settings > Advanced > Sources > Import / export source list; Governments > Statistics inputs.",
   "expected": "Hint names country_iso3 and the accepted forms; placeholders use alpha-3 or a name.",
   "actual": "'Country is a 2-letter code.' with a column list lacking country_iso3; placeholders 'FR or all' and 'FR'.",
   "evidence": "src/static/index.html:2529-2533, 891, 897."},
  {"title": "Governments > Law hovers keep the previous language after a bare language switch",
   "severity": "P3", "step_ids": ["L13"],
   "repro": "Governments > Law open in en, switch to fr/ar/zh from the top-bar menu, hover GBR/DEU/EUU without reloading.",
   "expected": "Hover names in the new language, as World coverage now does.",
   "actual": "'United Kingdom', 'Germany', 'European Union — not an ISO code' until a reload.",
   "evidence": "res-L13-fr.json / -ar / -zh 'bare_switch_law'; frozen-locale family noted in app-boot.js oo:langchange handler."},
  {"title": "Map Worldview picker lists countries by name only, ordered by the alpha-2 key",
   "severity": "P3", "step_ids": ["L7", "L11"],
   "repro": "Open any ooMap (World map, Governments > Map) and read the Worldview <select>.",
   "expected": "Q308: pickers ordered by localised name with the code as a secondary column.",
   "actual": "'Argentina, Bangladesh, Brazil, China, Germany, Egypt, Spain, France, United Kingdom, Greece …' (AR, BD, BR, CN, DE, EG, ES, FR, GB, GR order), no codes.",
   "evidence": "res-L7.json map_controls_text; src/static/app-map.js:349-355, 788."},
  {"title": "Untranslated English on row-L surfaces in fr/ar",
   "severity": "P3", "step_ids": ["L5", "L13"],
   "repro": "Switch to ar or fr; Library > World coverage; Settings > Advanced > Sources.",
   "expected": "Surface chrome translated ×12.",
   "actual": "'Top country: … sources, …% of located within the 12% guard …', 'Not covered (43)', 'Antarctica' (coverage); 'NAME', 'PRI', 'source(s) · showing 1–50', 'enabled source(s) in languages we can't analyse yet' (sources); 'Law changed (fr)' (Home).",
   "evidence": "L6-DEU-tip-ar.png, L13-src-country-filter-ar.png, L13-home-law-card-fr.png."}
 ],
 "not_measurable": [
  "Real World Bank country figures and real market series (the gate's 'walked with real data' clause): no egress here; the renderers were exercised with SYNTHETIC values pushed through the app's own parsers (parse_worldbank, parse_mcs_csv).",
  "Everything after 'Go online' in L11 (the World Bank load, the background collection it starts): consent popup screenshotted and cancelled.",
  "L7 point-drawn small-territory tooltip: no territory with data is drawn as a point in this corpus.",
  "L8 'By city' table: the seeded sources carry no city.",
  "L3 language with no two-letter code (e.g. 'pcm'): no such source language in this corpus (all 79 languages had a 639-2/T code).",
  "ANT (Netherlands Antilles) disclosure: no ANT row in the data; XKX was seen on Governments (see defects).",
  "Native SVG map tooltips are not painted by headless Chromium; their text was read from the hovered element's <title>.",
  "Q309 filename-rule test, loader/no-rewrite and payload/parameter clauses, P298 cross-check: repository/API behaviour, not clickable (per the step list)."
 ],
 "summary": "The click-through clause does NOT close. Law, the Agenda picker/list, the Sources table and pickers' order, Wikipedia/Living sources, the bulletin headings, the CSV export's two columns and the World-coverage hovers (including a bare en/fr/ar/zh switch) all show alpha-3 with the localised name in the hover, but several country surfaces still show two-letter codes: Insights > Map 'By country', Minerals supply, the Sources closed-filter label, the law-change card on Home and in the bulletin, the Groups refusal text, and 28 real ISO territories (Vatican City among them) missing from the alpha-3 table, which render as 'va'/'AX' hovering 'not a recognised country code'. Governments and Markets were walked only with synthetic data (no egress), so the gate's 'real data' clause also stays open."
}
json.dump(R, open("/tmp/claude-0/walk/L/report.json", "w"), ensure_ascii=False, indent=1)
print("ok", len(R["steps"]), len(R["defects"]))
