"""
Generator orchestrator: run per-country queries, normalise, dedup, emit YAML.

Open Omniscience - Global Intelligence Platform for Investigative Journalism
Copyright (C) 2026 Ideotion. GPL-3.0-or-later.

The HTTP transport is injected (``run_query``) so this orchestration is fully
unit-testable with fixtures; the CLI (scripts/build_world_news_catalog.py)
supplies a real Wikidata-backed ``run_query``. Output is the same ``{"sources":
[...]}`` YAML shape the seeder already understands.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable
from pathlib import Path

import yaml

from src.catalog.normalize import dedup_entries
from src.catalog.wikidata import parse_results

DEFAULT_QUERY_CONFIG = Path(__file__).resolve().parents[2] / "configs" / "catalog_query.yml"

# Signature of the injected transport: (country_code, type_qids) -> WDQS JSON dict.
RunQuery = Callable[[str, list[str]], dict]


def load_query_config(path: Path | None = None) -> dict:
    """Load the query config (label language, row limit, and the per-bucket specs)."""
    path = path or DEFAULT_QUERY_CONFIG
    data = yaml.safe_load(Path(path).read_text("utf-8")) or {}
    specs = []
    for s in data.get("specs", []):
        if isinstance(s, dict) and s.get("source_type") and s.get("type_qids"):
            specs.append({
                "source_type": str(s["source_type"]),
                "type_qids": [str(q) for q in s["type_qids"]],
                "tags": [str(t) for t in (s.get("tags") or [])],
            })
    return {
        "label_lang": str(data.get("label_lang", "en")),
        "limit": int(data.get("limit", 2000)),
        "specs": specs,
    }


def generate_catalog(
    run_query: RunQuery,
    country_codes: Iterable[str],
    specs: list[dict],
    *,
    existing_domains: set[str] | None = None,
    sleep: Callable[[], None] | None = None,
    on_progress: Callable[[str, int], None] | None = None,
) -> dict:
    """Query every (country × spec), normalise, dedup, and return the catalog.

    Resilient: a failed query for one country/bucket is recorded and skipped, so a
    single outage never aborts a multi-hundred-country run.
    """
    all_entries: list[dict] = []
    errors: list[str] = []
    per_country: dict[str, int] = {}

    for cc in country_codes:
        cc = cc.lower()
        found = 0
        for spec in specs:
            try:
                payload = run_query(cc, spec["type_qids"])
            except Exception as exc:  # noqa: BLE001 - record + continue, never abort the run
                errors.append(f"{cc}/{spec['source_type']}: {exc}")
                continue
            entries = parse_results(
                payload, country_code=cc,
                source_type=spec["source_type"], tags=spec.get("tags"),
            )
            all_entries.extend(entries)
            found += len(entries)
            if sleep:
                sleep()
        per_country[cc] = found
        if on_progress:
            on_progress(cc, found)

    res = dedup_entries(all_entries, existing_domains)
    return {
        "sources": res["kept"],
        "per_country_raw": per_country,
        "stats": {
            "raw_entries": len(all_entries),
            "kept": len(res["kept"]),
            "skipped_existing": res["skipped_existing"],
            "skipped_dupes": res["skipped_dupes"],
            "countries_queried": len(per_country),
            "errors": errors,
        },
    }


def write_catalog_yaml(path: Path, sources: list[dict], *, header: str | None = None) -> Path:
    """Write ``{"sources": [...]}`` YAML with an explanatory header comment."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    note = header or (
        "Generated by scripts/build_world_news_catalog.py from Wikidata (CC0).\n"
        "News organisations + official institutions by country. Re-run to refresh.\n"
        "Social networks are excluded. Edit configs/catalog_query.yml to tune types."
    )
    body = yaml.safe_dump({"sources": sources}, allow_unicode=True, sort_keys=False, width=4096)
    path.write_text("# " + note.replace("\n", "\n# ") + "\n\n" + body, "utf-8")
    return path
