"""Offline IP geolocation (data-architecture Slice 6b).

Open Omniscience - Global Intelligence Platform for Investigative Journalism
Copyright (C) 2026 Ideotion. GPL-3.0-or-later.

Proves the lookup is offline (zero sockets), honest when no DB / unknown IP (never a
fabricated coordinate), handles IPv4 + IPv6, and prefers a city DB but falls back to
country. The fixtures below are TINY, use RFC-5737/3849 documentation addresses, and are
NOT real geolocation data -- the real DB-IP table is generated by scripts/build_ip_geo.py.
"""

from __future__ import annotations

import socket

import pytest

from src.geo import ip_geo


@pytest.fixture(autouse=True)
def _clear_cache(monkeypatch):
    ip_geo._country_ranges.cache_clear()
    monkeypatch.delenv("OO_IP_GEO_DB", raising=False)
    monkeypatch.delenv("OO_IP_GEO_CITY_DB", raising=False)
    yield
    ip_geo._country_ranges.cache_clear()


def _country_fixture(tmp_path):
    p = tmp_path / "country.csv"
    p.write_text(
        "1.0.0.0,1.0.0.255,us\n"
        "203.0.113.0,203.0.113.255,fr\n"
        "2001:db8::,2001:db8::ffff,de\n",
        encoding="utf-8",
    )
    return p


def test_country_lookup_ipv4_and_ipv6(tmp_path, monkeypatch):
    monkeypatch.setenv("OO_IP_GEO_DB", str(_country_fixture(tmp_path)))
    r = ip_geo.lookup("203.0.113.10")
    assert r["country"] == "fr"
    assert r["level"] == "country"
    assert r["db_vintage"] == ip_geo.IP_GEO_AS_OF
    assert "DB-IP" in r["attribution"]
    assert "not proof" in r["caveat"]
    r6 = ip_geo.lookup("2001:db8::5")
    assert r6["country"] == "de" and r6["level"] == "country"


def test_unknown_ip_is_unavailable_never_guessed(tmp_path, monkeypatch):
    monkeypatch.setenv("OO_IP_GEO_DB", str(_country_fixture(tmp_path)))
    r = ip_geo.lookup("8.8.8.8")  # not in the fixture ranges
    assert r["level"] == "unavailable"
    assert r["country"] is None and r["lat"] is None and r["lon"] is None
    assert r["reason"] == "IP not in DB"


def test_no_db_is_unavailable_honestly(tmp_path, monkeypatch):
    # A bundled DB now ships, so point the override at a NONEXISTENT path to exercise the
    # honest no-DB state (env set + file missing -> _country_db_path returns None).
    monkeypatch.setenv("OO_IP_GEO_DB", str(tmp_path / "does-not-exist.csv"))
    r = ip_geo.lookup("203.0.113.10")
    assert r["level"] == "unavailable"
    assert r["reason"] == "no geo DB bundled"


def test_no_ip_and_invalid_ip_are_unavailable(tmp_path, monkeypatch):
    monkeypatch.setenv("OO_IP_GEO_DB", str(_country_fixture(tmp_path)))
    assert ip_geo.lookup(None)["reason"] == "no IP captured"
    assert ip_geo.lookup("not-an-ip")["reason"] == "not a valid IP"


def test_lookup_makes_no_network_call(tmp_path, monkeypatch):
    monkeypatch.setenv("OO_IP_GEO_DB", str(_country_fixture(tmp_path)))

    def _boom(*a, **k):  # any socket creation during a lookup is a bug
        raise AssertionError("ip_geo.lookup attempted a network socket")

    monkeypatch.setattr(socket, "socket", _boom)
    r = ip_geo.lookup("1.0.0.7")
    assert r["country"] == "us"


def test_city_db_preferred_then_country_fallback(tmp_path, monkeypatch):
    monkeypatch.setenv("OO_IP_GEO_DB", str(_country_fixture(tmp_path)))
    # No city DB -> country level for an in-country-range IP.
    assert ip_geo.lookup("1.0.0.7")["level"] == "country"
    # Add a city DB (dbip-city-lite layout) -> city level with its own lat/lon.
    city = tmp_path / "city.csv"
    city.write_text("9.9.9.0,9.9.9.255,NA,us,CA,Exampleville,37.75,-122.41\n", encoding="utf-8")
    monkeypatch.setenv("OO_IP_GEO_CITY_DB", str(city))
    r = ip_geo.lookup("9.9.9.9")
    assert r["level"] == "city"
    assert r["lat"] == 37.75 and r["lon"] == -122.41
    assert r["place"] == "Exampleville"


def test_freshness_reports_bundled_within_a_sane_window():
    # The real DB-IP CC BY 4.0 country table IS bundled now (data/dbip_country_lite.csv.gz).
    fr = ip_geo.freshness()
    assert fr["bundled"] is True
    assert fr["as_of"] == ip_geo.IP_GEO_AS_OF
    assert ip_geo.IP_GEO_AS_OF != "unbundled"
    # Vintage is a real YYYY-MM within ~18 months (mirrors the CATALOG_AS_OF freshness gate).
    assert isinstance(fr.get("age_months"), int)
    assert -1 <= fr["age_months"] <= 18, f"geo DB vintage too old: {fr}"


def test_real_bundled_db_resolves_known_ips_offline(monkeypatch):
    # End-to-end against the real bundled table (no env override). Counts as the bundle
    # smoke test: known public IPs resolve to a 2-letter country, fully offline.
    ip_geo._country_ranges.cache_clear()

    def _boom(*a, **k):
        raise AssertionError("real-DB lookup attempted a network socket")

    monkeypatch.setattr(socket, "socket", _boom)
    r = ip_geo.lookup("8.8.8.8")  # Google public DNS
    assert r["level"] == "country"
    assert isinstance(r["country"], str) and len(r["country"]) == 2
    assert r["db_vintage"] == ip_geo.IP_GEO_AS_OF
    assert "DB-IP" in r["attribution"]
    # IPv6 resolves too (the bundled table carries both families).
    r6 = ip_geo.lookup("2001:4860:4860::8888")
    assert r6["level"] == "country" and len(r6["country"]) == 2
    ip_geo._country_ranges.cache_clear()
