"""baseline schema v0.4

Revision ID: 6ae5766d3136
Revises: 
Create Date: 2026-06-04 16:48:09.108433
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae5766d3136'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodity_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=True),
    sa.Column('observed_on', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commodity_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commodity_prices_observed_on'), ['observed_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_commodity_prices_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_commodity_symbol_date', ['symbol', 'observed_on'], unique=False)

    op.create_table('external_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('credibility_score', sa.Float(), nullable=True),
    sa.Column('political_bias', sa.Float(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('alexa_rank', sa.Integer(), nullable=True),
    sa.Column('social_media_followers', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    with op.batch_alter_table('external_sources', schema=None) as batch_op:
        batch_op.create_index('idx_external_source_country', ['country'], unique=False)
        batch_op.create_index('idx_external_source_credibility', ['credibility_score'], unique=False)
        batch_op.create_index('idx_external_source_domain', ['domain'], unique=True)
        batch_op.create_index('idx_external_source_name', ['name'], unique=False)
        batch_op.create_index('idx_external_source_type', ['source_type'], unique=False)
        batch_op.create_index('idx_external_source_verified', ['is_verified'], unique=False)

    op.create_table('keyword_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['keyword_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('link_classification_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('pattern', sa.String(length=500), nullable=False),
    sa.Column('classification_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_name')
    )
    with op.batch_alter_table('link_classification_rules', schema=None) as batch_op:
        batch_op.create_index('idx_link_classification_active', ['is_active'], unique=False)
        batch_op.create_index('idx_link_classification_priority', ['priority'], unique=False)
        batch_op.create_index('idx_link_classification_rule_name', ['rule_name'], unique=True)
        batch_op.create_index('idx_link_classification_type', ['classification_type'], unique=False)

    op.create_table('source_credibility_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('factor', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('is_inverse', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_name')
    )
    with op.batch_alter_table('source_credibility_rules', schema=None) as batch_op:
        batch_op.create_index('idx_credibility_rule_active', ['is_active'], unique=False)
        batch_op.create_index('idx_credibility_rule_factor', ['factor'], unique=False)
        batch_op.create_index('idx_credibility_rule_name', ['rule_name'], unique=True)

    op.create_table('source_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_tag_based', sa.Boolean(), nullable=True),
    sa.Column('tag_pattern', sa.String(length=500), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('rate_limit_ms', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('rss_url', sa.String(length=500), nullable=True),
    sa.Column('rate_limit_ms', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('reliability_score', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('update_frequency', sa.Integer(), nullable=True),
    sa.Column('cacheability', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index('idx_source_country', ['country'], unique=False)
        batch_op.create_index('idx_source_domain', ['domain'], unique=True)
        batch_op.create_index('idx_source_enabled', ['enabled'], unique=False)
        batch_op.create_index('idx_source_language', ['language'], unique=False)
        batch_op.create_index('idx_source_priority', ['priority'], unique=False)
        batch_op.create_index('idx_source_region', ['region'], unique=False)
        batch_op.create_index('idx_source_reliability', ['reliability_score'], unique=False)
        batch_op.create_index('idx_source_type', ['source_type'], unique=False)

    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('canonical_url', sa.String(length=1000), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('compressed_content', sa.LargeBinary(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('reading_time', sa.Integer(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index('idx_article_author', ['author'], unique=False)
        batch_op.create_index('idx_article_canonical_url', ['canonical_url'], unique=False)
        batch_op.create_index('idx_article_content', ['content'], unique=False)
        batch_op.create_index('idx_article_country', ['country'], unique=False)
        batch_op.create_index('idx_article_country_language', ['country', 'language'], unique=False)
        batch_op.create_index('idx_article_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_article_hash', ['hash'], unique=True)
        batch_op.create_index('idx_article_language', ['language'], unique=False)
        batch_op.create_index('idx_article_language_region', ['language', 'region'], unique=False)
        batch_op.create_index('idx_article_published_at', ['published_at'], unique=False)
        batch_op.create_index('idx_article_region', ['region'], unique=False)
        batch_op.create_index('idx_article_sentiment', ['sentiment_score'], unique=False)
        batch_op.create_index('idx_article_source_id', ['source_id'], unique=False)
        batch_op.create_index('idx_article_source_published', ['source_id', 'published_at'], unique=False)
        batch_op.create_index('idx_article_word_count', ['word_count'], unique=False)

    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('normalized_term', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('is_ngram', sa.Boolean(), nullable=True),
    sa.Column('ngram_size', sa.Integer(), nullable=True),
    sa.Column('is_entity', sa.Boolean(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['keyword_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.create_index('idx_keyword_category_id', ['category_id'], unique=False)
        batch_op.create_index('idx_keyword_frequency', ['frequency'], unique=False)
        batch_op.create_index('idx_keyword_is_entity', ['is_entity'], unique=False)
        batch_op.create_index('idx_keyword_is_ngram', ['is_ngram'], unique=False)
        batch_op.create_index('idx_keyword_language', ['language'], unique=False)
        batch_op.create_index('idx_keyword_normalized_term', ['normalized_term'], unique=False)
        batch_op.create_index('idx_keyword_term', ['term'], unique=False)

    op.create_table('source_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('is_accessible', sa.Boolean(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['external_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_articles', schema=None) as batch_op:
        batch_op.create_index('idx_source_article_accessible', ['is_accessible'], unique=False)
        batch_op.create_index('idx_source_article_hash', ['content_hash'], unique=True)
        batch_op.create_index('idx_source_article_published', ['published_at'], unique=False)
        batch_op.create_index('idx_source_article_source_id', ['source_id'], unique=False)
        batch_op.create_index('idx_source_article_url', ['url'], unique=True)

    op.create_table('source_group_association',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['source_groups.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'group_id')
    )
    with op.batch_alter_table('source_group_association', schema=None) as batch_op:
        batch_op.create_index('idx_source_group_group_id', ['group_id'], unique=False)
        batch_op.create_index('idx_source_group_source_id', ['source_id'], unique=False)

    op.create_table('source_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('robots_txt_url', sa.String(length=500), nullable=True),
    sa.Column('robots_allowed', sa.Boolean(), nullable=True),
    sa.Column('crawl_delay', sa.Integer(), nullable=True),
    sa.Column('sitemap_url', sa.String(length=500), nullable=True),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('social_twitter', sa.String(length=255), nullable=True),
    sa.Column('social_facebook', sa.String(length=500), nullable=True),
    sa.Column('social_linkedin', sa.String(length=500), nullable=True),
    sa.Column('alexa_rank', sa.Integer(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    with op.batch_alter_table('source_metadata', schema=None) as batch_op:
        batch_op.create_index('idx_metadata_country', ['country'], unique=False)
        batch_op.create_index('idx_metadata_language', ['language'], unique=False)
        batch_op.create_index('idx_metadata_robots_allowed', ['robots_allowed'], unique=False)
        batch_op.create_index('idx_metadata_source_id', ['source_id'], unique=True)

    op.create_table('article_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_analyses_article_id'), ['article_id'], unique=False)

    op.create_table('article_keyword_association',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'keyword_id')
    )
    with op.batch_alter_table('article_keyword_association', schema=None) as batch_op:
        batch_op.create_index('idx_article_keyword_article_id', ['article_id'], unique=False)
        batch_op.create_index('idx_article_keyword_keyword_id', ['keyword_id'], unique=False)

    op.create_table('article_keywords',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('first_position', sa.Integer(), nullable=True),
    sa.Column('last_position', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'keyword_id')
    )
    op.create_table('article_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('normalized_url', sa.String(length=1000), nullable=False),
    sa.Column('link_text', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('link_type', sa.String(length=50), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('external_source_id', sa.Integer(), nullable=True),
    sa.Column('source_article_id', sa.Integer(), nullable=True),
    sa.Column('is_followable', sa.Boolean(), nullable=True),
    sa.Column('is_working', sa.Boolean(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('redirect_url', sa.String(length=1000), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['external_source_id'], ['external_sources.id'], ),
    sa.ForeignKeyConstraint(['source_article_id'], ['source_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_links', schema=None) as batch_op:
        batch_op.create_index('idx_article_link_article_id', ['article_id'], unique=False)
        batch_op.create_index('idx_article_link_classification', ['classification'], unique=False)
        batch_op.create_index('idx_article_link_normalized_url', ['normalized_url'], unique=False)
        batch_op.create_index('idx_article_link_source_article_id', ['source_article_id'], unique=False)
        batch_op.create_index('idx_article_link_source_id', ['external_source_id'], unique=False)
        batch_op.create_index('idx_article_link_type', ['link_type'], unique=False)
        batch_op.create_index('idx_article_link_url', ['url'], unique=False)
        batch_op.create_index('idx_article_link_working', ['is_working'], unique=False)

    op.create_table('article_source_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_article_id', sa.Integer(), nullable=True),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('time_delta_days', sa.Float(), nullable=True),
    sa.Column('is_temporal_anomaly', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['article_links.id'], ),
    sa.ForeignKeyConstraint(['source_article_id'], ['source_articles.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['external_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_source_relationships', schema=None) as batch_op:
        batch_op.create_index('idx_article_source_rel_anomaly', ['is_temporal_anomaly'], unique=False)
        batch_op.create_index('idx_article_source_rel_article_id', ['article_id'], unique=False)
        batch_op.create_index('idx_article_source_rel_confidence', ['confidence_score'], unique=False)
        batch_op.create_index('idx_article_source_rel_link_id', ['link_id'], unique=False)
        batch_op.create_index('idx_article_source_rel_source_article_id', ['source_article_id'], unique=False)
        batch_op.create_index('idx_article_source_rel_source_id', ['source_id'], unique=False)
        batch_op.create_index('idx_article_source_rel_type', ['relationship_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_source_relationships', schema=None) as batch_op:
        batch_op.drop_index('idx_article_source_rel_type')
        batch_op.drop_index('idx_article_source_rel_source_id')
        batch_op.drop_index('idx_article_source_rel_source_article_id')
        batch_op.drop_index('idx_article_source_rel_link_id')
        batch_op.drop_index('idx_article_source_rel_confidence')
        batch_op.drop_index('idx_article_source_rel_article_id')
        batch_op.drop_index('idx_article_source_rel_anomaly')

    op.drop_table('article_source_relationships')
    with op.batch_alter_table('article_links', schema=None) as batch_op:
        batch_op.drop_index('idx_article_link_working')
        batch_op.drop_index('idx_article_link_url')
        batch_op.drop_index('idx_article_link_type')
        batch_op.drop_index('idx_article_link_source_id')
        batch_op.drop_index('idx_article_link_source_article_id')
        batch_op.drop_index('idx_article_link_normalized_url')
        batch_op.drop_index('idx_article_link_classification')
        batch_op.drop_index('idx_article_link_article_id')

    op.drop_table('article_links')
    op.drop_table('article_keywords')
    with op.batch_alter_table('article_keyword_association', schema=None) as batch_op:
        batch_op.drop_index('idx_article_keyword_keyword_id')
        batch_op.drop_index('idx_article_keyword_article_id')

    op.drop_table('article_keyword_association')
    with op.batch_alter_table('article_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_analyses_article_id'))

    op.drop_table('article_analyses')
    with op.batch_alter_table('source_metadata', schema=None) as batch_op:
        batch_op.drop_index('idx_metadata_source_id')
        batch_op.drop_index('idx_metadata_robots_allowed')
        batch_op.drop_index('idx_metadata_language')
        batch_op.drop_index('idx_metadata_country')

    op.drop_table('source_metadata')
    with op.batch_alter_table('source_group_association', schema=None) as batch_op:
        batch_op.drop_index('idx_source_group_source_id')
        batch_op.drop_index('idx_source_group_group_id')

    op.drop_table('source_group_association')
    with op.batch_alter_table('source_articles', schema=None) as batch_op:
        batch_op.drop_index('idx_source_article_url')
        batch_op.drop_index('idx_source_article_source_id')
        batch_op.drop_index('idx_source_article_published')
        batch_op.drop_index('idx_source_article_hash')
        batch_op.drop_index('idx_source_article_accessible')

    op.drop_table('source_articles')
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_index('idx_keyword_term')
        batch_op.drop_index('idx_keyword_normalized_term')
        batch_op.drop_index('idx_keyword_language')
        batch_op.drop_index('idx_keyword_is_ngram')
        batch_op.drop_index('idx_keyword_is_entity')
        batch_op.drop_index('idx_keyword_frequency')
        batch_op.drop_index('idx_keyword_category_id')

    op.drop_table('keywords')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('idx_article_word_count')
        batch_op.drop_index('idx_article_source_published')
        batch_op.drop_index('idx_article_source_id')
        batch_op.drop_index('idx_article_sentiment')
        batch_op.drop_index('idx_article_region')
        batch_op.drop_index('idx_article_published_at')
        batch_op.drop_index('idx_article_language_region')
        batch_op.drop_index('idx_article_language')
        batch_op.drop_index('idx_article_hash')
        batch_op.drop_index('idx_article_created_at')
        batch_op.drop_index('idx_article_country_language')
        batch_op.drop_index('idx_article_country')
        batch_op.drop_index('idx_article_content')
        batch_op.drop_index('idx_article_canonical_url')
        batch_op.drop_index('idx_article_author')

    op.drop_table('articles')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index('idx_source_type')
        batch_op.drop_index('idx_source_reliability')
        batch_op.drop_index('idx_source_region')
        batch_op.drop_index('idx_source_priority')
        batch_op.drop_index('idx_source_language')
        batch_op.drop_index('idx_source_enabled')
        batch_op.drop_index('idx_source_domain')
        batch_op.drop_index('idx_source_country')

    op.drop_table('sources')
    op.drop_table('source_groups')
    with op.batch_alter_table('source_credibility_rules', schema=None) as batch_op:
        batch_op.drop_index('idx_credibility_rule_name')
        batch_op.drop_index('idx_credibility_rule_factor')
        batch_op.drop_index('idx_credibility_rule_active')

    op.drop_table('source_credibility_rules')
    with op.batch_alter_table('link_classification_rules', schema=None) as batch_op:
        batch_op.drop_index('idx_link_classification_type')
        batch_op.drop_index('idx_link_classification_rule_name')
        batch_op.drop_index('idx_link_classification_priority')
        batch_op.drop_index('idx_link_classification_active')

    op.drop_table('link_classification_rules')
    op.drop_table('keyword_categories')
    with op.batch_alter_table('external_sources', schema=None) as batch_op:
        batch_op.drop_index('idx_external_source_verified')
        batch_op.drop_index('idx_external_source_type')
        batch_op.drop_index('idx_external_source_name')
        batch_op.drop_index('idx_external_source_domain')
        batch_op.drop_index('idx_external_source_credibility')
        batch_op.drop_index('idx_external_source_country')

    op.drop_table('external_sources')
    with op.batch_alter_table('commodity_prices', schema=None) as batch_op:
        batch_op.drop_index('ix_commodity_symbol_date')
        batch_op.drop_index(batch_op.f('ix_commodity_prices_symbol'))
        batch_op.drop_index(batch_op.f('ix_commodity_prices_observed_on'))

    op.drop_table('commodity_prices')
    # ### end Alembic commands ###
