"""
Diagnostics log: shareable, on-demand syntheses of back-end state.

Open Omniscience - Global Intelligence Platform for Investigative Journalism
Copyright (C) 2026 Ideotion. GPL-3.0-or-later.

The maintainer<->developer feedback channel (CLAUDE.md ruling 2026-06-10): the corpus is
private and local by design, so improving data-shaped behaviour (keyword grouping first)
needs an export the operator can *choose* to share. Precedent:
``data/source_preflight.jsonl`` plays this role for sources.

Honesty constraints (FUTURE_DEVELOPMENTS design):
- generated ON DEMAND only -- nothing is written or sent automatically;
- carries date, app version and corpus size so the reader knows the context;
- synthesizes, never editorialises: counts and structures, no scores;
- bounded (the same discipline as every other scan) and says so when capped.

A PACKAGE SINCE 2026-09-16 (Q1139 = a, the authorised mechanical split). It was one
6,741-line module; each submodule below is a CONTIGUOUS SLICE of it, verbatim.

THREE THINGS HERE ARE LOAD-BEARING, and each has a test.

(1) THE IMPORT ORDER IS THE ORIGINAL FILE ORDER. ``@router.<verb>`` fires at import
    time, so importing the slices in file order leaves ``router.routes`` identical
    element for element -- same paths, same methods, same names, same ORDER.
    ``test_diagnostics_split_is_route_neutral`` pins the whole table against a
    checked-in snapshot taken from the pre-split module.

(2) EVERY NAME THE PRE-SPLIT MODULE DEFINED IS RE-EXPORTED, because ``src.api.main``,
    ``src/backup/runlog.py`` and thirty test files reach for them through
    ``src.api.diagnostics``. ``test_diagnostics_package_reexports_every_submodule_name``
    asserts the re-export list is COMPLETE against the submodules themselves, so a name
    added to a slice cannot silently stop being importable from here.

(3) A RE-EXPORT IS A READ PATH, NEVER A WRITE PATH. ``monkeypatch.setattr`` against a
    name HERE rebinds this package's copy and the submodule that actually reads it goes
    on reading its own -- a silent no-op, which is the 2026-08-20 ``app.js``-split lesson
    (a split turns an assertion vacuous at every site at once) wearing a fixture's
    clothes. Patch the SUBMODULE that owns the name;
    ``test_no_test_monkeypatches_the_diagnostics_package`` fails on the next one.
"""

from __future__ import annotations

# ruff: noqa: I001 -- the submodule import ORDER below is the pre-split file order and
# is load-bearing: `@router.<verb>` fires at import time, so sorting these alphabetically
# would silently re-order `router.routes`. isort has no way to know that; this does.
# `test_diagnostics_split_is_route_neutral` pins the resulting table, order included.


from ._base import (
    _LOG,
    _MAX_KEYWORDS_PER_LANG,
    api_dir,
    package_source,
    router,
)
from .keywords import (
    _DIGEST_SAMPLE,
    _RING_CAND_MIN_ARTICLES,
    _RING_CAND_PER_LANG,
    _SW_CAND_MAX_LEN,
    _SW_CAND_MIN_ARTICLES,
    _SW_CAND_PER_LANG,
    _export_deadline_seconds,
    _families_summary,
    _group_entries_by_language,
    _in_batches,
    _keyword_zip,
    _keyword_zip_families_cap,
    _keyword_zip_max_bytes,
    _quantiles,
    _ring_candidates,
    _safe_lang_filename,
    _stopword_candidates,
    keyword_log,
    keyword_selftest,
)
from .discovery import (
    _ENRICH_JOB,
    _WORLD_DISCOVERY_JOB,
    _enrich_source_types_worker,
    _world_discovery_worker,
    discover_sources_endpoint,
    discover_world_cancel,
    discover_world_sources,
    discover_world_status,
    enrich_source_types,
    enrich_source_types_status,
    enrich_sources,
)
from .evals import (
    PerceptionEvalLiveBody,
    _GoldBuilderSaveBody,
    _run_journal_raw,
    gold_builder_sample,
    gold_builder_save,
    ir_eval,
    ir_eval_selftest,
    keyword_triage_selftest,
    kpi,
    merge_diag,
    perception_eval_live,
    perception_eval_live_last,
    perception_eval_selftest,
    recursive_loop,
    run_journal,
    run_timeline,
    search_timing,
    search_timing_selftest,
)
from .corpus import (
    CardAuditRunBody,
    _CARD_AUDIT_JOB,
    _card_audit_worker,
    _leads_quality_budget_s,
    article_length,
    bulletin_language,
    bulletin_language_selftest,
    card_audit,
    card_audit_cancel,
    card_audit_download,
    card_audit_preflight,
    card_audit_run,
    card_audit_status,
    criteria_calibration,
    home_card_diagnostics,
    keyword_engine,
    keyword_growth,
    leads_quality,
    lemma_preview,
    month_occupancy,
    non_article_scan,
    power_profile,
    power_profile_selftest,
)
from .sources import (
    qualification_integrity,
    source_audit,
    source_audit_selftest,
    source_qualification_export,
    source_quality,
)
from .dates import (
    date_extraction_log,
)
from .performance import (
    ai_activity,
    ai_activity_selftest,
    benchmark_report,
    bulletin_preview,
    llm_bench,
    llm_throughput,
    llm_throughput_selftest,
    performance_report,
    rollup_benchmark,
    source_coverage_benchmark,
)
from .system import (
    _FrontendError,
    _p0_validation_last,
    _session_forensics_text,
    columnar_status,
    corpus_integrity_report,
    data_dir_persistence_report,
    elections_coverage_floor,
    external_freshness,
    frontend_errors,
    law_coverage,
    law_ingest,
    network_preflight_log,
    report_frontend_error,
    request_latency,
    schema_drift_report,
    session_forensics_report,
    slow_queries,
    soak_window_report,
    stall_forensics_report,
    storage_composition_report,
    storage_footprint_report,
    windows_locks_report,
    write_gate_report,
)
from .bundle import (
    _ALL_DIAG_DEADLINE_SENTINEL,
    _ALL_DIAG_JOB,
    _ALL_DIAG_TRIM_AFTER_KB,
    _ALL_DIAG_VOLUMES_LOCK,
    _DIAG_COVERAGE_EXEMPT,
    _DIAG_COVERAGE_MAP,
    _DIAG_SIBLING_FILES,
    _MEMBER_SPOOL_MAX,
    _RssProbe,
    _UNSERIALISABLE,
    _all_diag_db_member_deadline_s,
    _all_diag_err_str,
    _all_diag_member_max_bytes,
    _all_diag_nondb_member_deadline_s,
    _all_diagnostics_dir,
    _all_diagnostics_manifest,
    _all_diagnostics_members,
    _all_diagnostics_volumes_dir,
    _all_diagnostics_worker,
    _bundle_exclusive_window,
    _corpus_counters_safe,
    _country_code_scan,
    _cpu_model_safe,
    _debug_bundle_member_budget_s,
    _diagnostics_coverage_report,
    _disk_rotational_probe,
    _ensure_volume_set,
    _fixity_bundle_member,
    _hardware_profile,
    _member_bytes,
    _member_default,
    _member_touches_db,
    _newest_all_diagnostics_archive,
    _rss_peak_kb,
    _run_nondb_member_bounded,
    _schema_head_safe,
    _trim_after_heavy_member,
    _write_all_diagnostics_zip,
    _write_member,
    _write_member_omission,
    all_diagnostics,
    all_diagnostics_job_download,
    all_diagnostics_job_start,
    all_diagnostics_job_status,
    all_diagnostics_volume_download,
    all_diagnostics_volumes,
    debug_bundle,
)
from .p0 import (
    P0ValidationBody,
    _P0_VALIDATION_JOB,
    _p0_scrub,
    _p0_validation_worker,
    p0_validation_cancel,
    p0_validation_download,
    p0_validation_last,
    p0_validation_start,
    p0_validation_status,
)
from .keyword_triage import (
    KeywordTriageRunBody,
    _KEYWORD_TRIAGE_JOB,
    _keyword_triage_worker,
    keyword_triage_cancel,
    keyword_triage_download,
    keyword_triage_last,
    keyword_triage_proposal,
    keyword_triage_run,
    keyword_triage_status,
)
from .source_tags import (
    SourceTagsRunBody,
    _SOURCE_TAGS_JOB,
    _source_tags_worker,
    source_tags_cancel,
    source_tags_download,
    source_tags_last,
    source_tags_run,
    source_tags_selftest,
    source_tags_status,
)
from .perception import (
    PerceptionExtractRunBody,
    _PERCEPTION_EXTRACT_JOB,
    _perception_extract_worker,
    perception_extract_cancel,
    perception_extract_download,
    perception_extract_gate,
    perception_extract_last,
    perception_extract_run,
    perception_extract_status,
)
from .ai_check import (
    AiCheckRunBody,
    _AI_CHECK_JOB,
    _ai_check_worker,
    ai_check_cancel,
    ai_check_download,
    ai_check_last,
    ai_check_run,
    ai_check_status,
)
from .ai import (
    QualificationAssistBody,
    _SCRIPT_OF_LANG,
    ai_diagnostics,
    qualification_assist_last,
    qualification_assist_run,
    qualification_assist_selftest,
)
from .ai_coordinator import (
    _AI_COORDINATOR_JOB,
    _ai_coordinator_worker,
    ai_coordinator_cancel,
    ai_coordinator_run,
    ai_coordinator_status,
)
from .model_bench import (
    ModelBenchAnchorsBody,
    ModelBenchBatchBody,
    ModelBenchRunBody,
    _MODEL_BENCH_JOB,
    _model_bench_worker,
    model_bench_anchors,
    model_bench_batch,
    model_bench_build_batch,
    model_bench_cancel,
    model_bench_download,
    model_bench_gates,
    model_bench_last,
    model_bench_run,
    model_bench_save_anchors,
    model_bench_status,
)

# LAST, and deliberately so (2026-09-16, gate row K). `@router.<verb>` fires at import
# time, so importing a new slice here APPENDS its route and moves none of the 131 the
# split guard pins by position. A slice inserted anywhere else would renumber the table
# and make that guard's diff unreadable.
from .country_codes import (
    country_code_duplicates,
)

# LAST again, for the same reason (2026-09-18, B5 / row S): a slice imported here appends
# its route to the end of the table, where the split guard's `_ADDED_AFTER_THE_SPLIT`
# list records it by name. Adding this endpoint to `sources.py` instead renumbered 84
# positions the snapshot pins -- which is the failure the comment above describes,
# observed.
from .qualification_merge import (
    _MAX_MERGE_UPLOADS,
    source_qualification_merge,
)

__all__ = [
    "_MAX_MERGE_UPLOADS",
    "AiCheckRunBody",
    "CardAuditRunBody",
    "KeywordTriageRunBody",
    "ModelBenchAnchorsBody",
    "ModelBenchBatchBody",
    "ModelBenchRunBody",
    "P0ValidationBody",
    "PerceptionEvalLiveBody",
    "PerceptionExtractRunBody",
    "QualificationAssistBody",
    "SourceTagsRunBody",
    "_AI_CHECK_JOB",
    "_AI_COORDINATOR_JOB",
    "_ALL_DIAG_DEADLINE_SENTINEL",
    "_ALL_DIAG_JOB",
    "_ALL_DIAG_TRIM_AFTER_KB",
    "_ALL_DIAG_VOLUMES_LOCK",
    "_CARD_AUDIT_JOB",
    "_DIAG_COVERAGE_EXEMPT",
    "_DIAG_COVERAGE_MAP",
    "_DIAG_SIBLING_FILES",
    "_DIGEST_SAMPLE",
    "_ENRICH_JOB",
    "_FrontendError",
    "_GoldBuilderSaveBody",
    "_KEYWORD_TRIAGE_JOB",
    "_LOG",
    "_MAX_KEYWORDS_PER_LANG",
    "_MEMBER_SPOOL_MAX",
    "_MODEL_BENCH_JOB",
    "_P0_VALIDATION_JOB",
    "_PERCEPTION_EXTRACT_JOB",
    "_RING_CAND_MIN_ARTICLES",
    "_RING_CAND_PER_LANG",
    "_RssProbe",
    "_SCRIPT_OF_LANG",
    "_SOURCE_TAGS_JOB",
    "_SW_CAND_MAX_LEN",
    "_SW_CAND_MIN_ARTICLES",
    "_SW_CAND_PER_LANG",
    "_UNSERIALISABLE",
    "_WORLD_DISCOVERY_JOB",
    "_ai_check_worker",
    "_ai_coordinator_worker",
    "_all_diag_db_member_deadline_s",
    "_all_diag_err_str",
    "_all_diag_member_max_bytes",
    "_all_diag_nondb_member_deadline_s",
    "_all_diagnostics_dir",
    "_all_diagnostics_manifest",
    "_all_diagnostics_members",
    "_all_diagnostics_volumes_dir",
    "_all_diagnostics_worker",
    "_bundle_exclusive_window",
    "_card_audit_worker",
    "_corpus_counters_safe",
    "_country_code_scan",
    "_cpu_model_safe",
    "_debug_bundle_member_budget_s",
    "_diagnostics_coverage_report",
    "_disk_rotational_probe",
    "_enrich_source_types_worker",
    "_ensure_volume_set",
    "_export_deadline_seconds",
    "_families_summary",
    "_fixity_bundle_member",
    "_group_entries_by_language",
    "_hardware_profile",
    "_in_batches",
    "_keyword_triage_worker",
    "_keyword_zip",
    "_keyword_zip_families_cap",
    "_keyword_zip_max_bytes",
    "_leads_quality_budget_s",
    "_member_bytes",
    "_member_default",
    "_member_touches_db",
    "_model_bench_worker",
    "_newest_all_diagnostics_archive",
    "_p0_scrub",
    "_p0_validation_last",
    "_p0_validation_worker",
    "_perception_extract_worker",
    "_quantiles",
    "_ring_candidates",
    "_rss_peak_kb",
    "_run_journal_raw",
    "_run_nondb_member_bounded",
    "_safe_lang_filename",
    "_schema_head_safe",
    "_session_forensics_text",
    "_source_tags_worker",
    "_stopword_candidates",
    "_trim_after_heavy_member",
    "_world_discovery_worker",
    "_write_all_diagnostics_zip",
    "_write_member",
    "_write_member_omission",
    "ai_activity",
    "ai_activity_selftest",
    "ai_check_cancel",
    "ai_check_download",
    "ai_check_last",
    "ai_check_run",
    "ai_check_status",
    "ai_coordinator_cancel",
    "ai_coordinator_run",
    "ai_coordinator_status",
    "ai_diagnostics",
    "all_diagnostics",
    "all_diagnostics_job_download",
    "all_diagnostics_job_start",
    "all_diagnostics_job_status",
    "all_diagnostics_volume_download",
    "all_diagnostics_volumes",
    "api_dir",
    "article_length",
    "benchmark_report",
    "bulletin_language",
    "bulletin_language_selftest",
    "bulletin_preview",
    "card_audit",
    "card_audit_cancel",
    "card_audit_download",
    "card_audit_preflight",
    "card_audit_run",
    "card_audit_status",
    "columnar_status",
    "corpus_integrity_report",
    "country_code_duplicates",
    "criteria_calibration",
    "data_dir_persistence_report",
    "date_extraction_log",
    "debug_bundle",
    "discover_sources_endpoint",
    "discover_world_cancel",
    "discover_world_sources",
    "discover_world_status",
    "elections_coverage_floor",
    "enrich_source_types",
    "enrich_source_types_status",
    "enrich_sources",
    "external_freshness",
    "frontend_errors",
    "gold_builder_sample",
    "gold_builder_save",
    "home_card_diagnostics",
    "ir_eval",
    "ir_eval_selftest",
    "keyword_engine",
    "keyword_growth",
    "keyword_log",
    "keyword_selftest",
    "keyword_triage_cancel",
    "keyword_triage_download",
    "keyword_triage_last",
    "keyword_triage_proposal",
    "keyword_triage_run",
    "keyword_triage_selftest",
    "keyword_triage_status",
    "kpi",
    "law_coverage",
    "law_ingest",
    "leads_quality",
    "lemma_preview",
    "llm_bench",
    "llm_throughput",
    "llm_throughput_selftest",
    "merge_diag",
    "model_bench_anchors",
    "model_bench_batch",
    "model_bench_build_batch",
    "model_bench_cancel",
    "model_bench_download",
    "model_bench_gates",
    "model_bench_last",
    "model_bench_run",
    "model_bench_save_anchors",
    "model_bench_status",
    "month_occupancy",
    "network_preflight_log",
    "non_article_scan",
    "p0_validation_cancel",
    "p0_validation_download",
    "p0_validation_last",
    "p0_validation_start",
    "p0_validation_status",
    "package_source",
    "perception_eval_live",
    "perception_eval_live_last",
    "perception_eval_selftest",
    "perception_extract_cancel",
    "perception_extract_download",
    "perception_extract_gate",
    "perception_extract_last",
    "perception_extract_run",
    "perception_extract_status",
    "performance_report",
    "power_profile",
    "power_profile_selftest",
    "qualification_assist_last",
    "qualification_assist_run",
    "qualification_assist_selftest",
    "qualification_integrity",
    "recursive_loop",
    "report_frontend_error",
    "request_latency",
    "rollup_benchmark",
    "router",
    "run_journal",
    "run_timeline",
    "schema_drift_report",
    "search_timing",
    "search_timing_selftest",
    "session_forensics_report",
    "slow_queries",
    "soak_window_report",
    "source_audit",
    "source_audit_selftest",
    "source_coverage_benchmark",
    "source_qualification_export",
    "source_qualification_merge",
    "source_quality",
    "source_tags_cancel",
    "source_tags_download",
    "source_tags_last",
    "source_tags_run",
    "source_tags_selftest",
    "source_tags_status",
    "stall_forensics_report",
    "storage_composition_report",
    "storage_footprint_report",
    "windows_locks_report",
    "write_gate_report",
]
