import json
S = "/tmp/claude-0/walk/N/shots/"
report = {
 "row": "N",
 "environment": {
  "encrypted": True,
  "seed": "Main store (:8830): scripts/ui_clickthrough_seed.py default STATE C (440 language-pool articles) + docs/audit/cross-language-lens-clickthrough-2026-09-17/concept_fixture.py (9 articles, run once), both with OO_DB_PASSPHRASE set and OO_DB_PLAINTEXT unset -> 462 articles, file header is ciphertext; booted with neither variable, so it started LOCKED and was unlocked through #pw/#btn-unlock. N13 stand-in store (:8831): the same seed + fixture written by the PRE-S8 code (git archive 1af520c^ into the scratch dir, encrypted), then served by current main (origin/main 462145c) so its search index was the old shape.",
  "ports": [8830, 8831],
  "scratch_dir": "/tmp/claude-0/walk/N/",
  "notes": "Deviation from the sheet: Part A ran on an ENCRYPTED seeded store on :8830 (not a plaintext throwaway on :8010) as the harness asked; the numbers match the sandbox ones exactly (160/156/161/7/40-of-44). Part B (the operator's own encrypted install with a real corpus) does not exist here: N12 was measured on the encrypted seeded store and N13 on an encrypted store indexed by the pre-S8 code. Airplane mode stayed ON throughout (plane fill=currentColor, /api/system/network online:false); no consent popup was raised by any step, the coachmark's 'Go online' was never pressed (only its 'Not now'). Chromium 1440x950 main pass; fr, ar, zh, ja locale pass; 375x800 en pass. Final evidence runs: R-en-all.json, R-loc-fr-ar-zh-ja.json, R-ar-ins*.json, R-375.json, R-n13.json, R-misc.json (dev iterations in dev-runs/). Screenshots in shots/. Servers (PIDs 3841, 9332, 10503) killed."
 },
 "steps": [
  {"id": "N1", "result": "pass", "locales": ["en"], "screenshot": S+"N-N1-lock-en.png",
   "observed": "Seed printed 'ui_clickthrough_seed: STATE C seeded.' and the fixture 'added 9 cross-language fixture articles' (seed2.log, fixture2.log). Encrypted boot landed on /unlock (lock form shown, screenshot N-N1-lock-en.png); after unlock -> /#home, no guide wizard, #net-toggle plane FILLED (fill=currentColor, title 'Airplane mode — filled means offline…'), /api/system/network {online:false}. The airplane coachmark appeared and was dismissed with its own 'Not now'."},
  {"id": "N2", "result": "pass", "locales": ["en"], "screenshot": S+"N-N2-articles-default-en.png",
   "observed": "New browser tab ?analyze=climate. Grey block exactly 'climate also matched as the concept “climate” — en: climate · fr: climat · de: klima · es: clima · it: clima · pt: clima · nl: klimaat · ar: مناخ · ru: климат', then 'Count each form', then the caveat ending 'Show only the words I typed'. Total line '160 Articles · Open an article…'. Language chips fra 29 · deu 28 · ara 27 · por 27 · rus 27 · eng 21 · spa 1 (sum 160, no zho). Columns Title/Source/Language/Published/Top keyword; 50/50 rows carry a 3-letter code; hovering deu/fra shows 'German'/'French' in the #oo-tip bubble. Default 'Relevance / recency' is NOT date-ordered while 'Interleave by date' is aria-pressed=true (recorded Q508 gap, see defects). Sort by Date: strictly newest->oldest with 7 languages mixed on the page, total still 160. Group by language: headings fra 9 · por 9 · rus 9 · eng 8 · ara 7 · deu 7 · spa 1 (largest first, ties alphabetical) = 50 rows, total line still 160; Interleave by date removes the headings. (Heading grammar reads 'spa 1 articles'.)"},
  {"id": "N3", "result": "pass", "locales": ["en"], "screenshot": S+"N-N3-formcounts-en.png",
   "observed": "'Counting…' then exactly 'climate 156 · climat 3 · clima 1 · klima 1 · klimaat 0 · климат 0 · مناخ 0 · 160 articles in total, counted once each These figures overlap: …do not add up to it.' In-total 160 = list total; forms sum 161 > 160; no 'N of M forms counted'; no '—'. First browser tab, palette 'Run the full Boolean search for “climate”' -> #search: '160 result(s) (showing 50)'."},
  {"id": "N4", "result": "pass", "locales": ["en"], "screenshot": S+"N-N4-literal-en.png",
   "observed": "Sentiment before 'n=21/160'. 'Show only the words I typed' -> URL ?analyze=climate&expand=0, block 'Showing only the words you typed. Search the concept in every language', total 156 (= climate 156), chips lose spa. Trend view buttons only 'Counts', 'Indexed'. Sentiment 'n=21/156'. F5 lands on Overview; Articles still literal, 156. Same URL pasted into a new tab: literal, 156. 'Search the concept in every language' removes expand=0, total 160, full block back."},
  {"id": "N5", "result": "fail", "locales": ["en"], "screenshot": S+"N-race-en-N5.png",
   "observed": "FIRST PAINT WRONG (see the P1 race defect): the new 'Analysis: “election”' tab had the election tab active and the header “election”, but the Articles panel showed the CLIMATE result (climate grey block, climate chips, 160) until the election tab in the strip was clicked again. After that click everything matched the sheet: block 'election denotes several concepts, so it was not expanded. Search one of them: “election” · “public election”' with the ring caveat still printed under it (reads as a contradiction; known note 4); total 20, chips eng 20. Pick “public election” -> 'election: searching the concept “public election”, which you chose — en: … zh: 選舉, 选举, …' + 'Show all senses', URL sense=election%3Apublic-election, total 216, chips ara/deu/spa/fra/por/rus/zho 28 + eng 20. Limit sentence 'The search was widened to the most-mentioned forms only. Turn the limit off… Search every form' carries no numbers; 'Count each form' ends '216 articles in total… · 40 of 44 forms counted' (only there). 'Search every form' -> URL cap=0, 'Searching every form of the concept. Limit the search…', total 216 (not smaller), readout has no '… of 44'. zho was ALREADY in the chips with the limit ON (选举 28 is among the 40 kept), so the limit did not drop Chinese here. 'Limit…' removes cap=0; 'Show all senses' removes sense=, back to the first sentence, total 20."},
  {"id": "N6", "result": "fail", "locales": ["en"], "screenshot": S+"N-N6-legend-hidden-en.png",
   "observed": "By language draws stacked columns (7 area colours on the canvas), y axis from 0, legend eng/fra/deu/spa/ita/por; totals 'eng 3 · fra 3 · deu 1 · spa 1 · ita 1 · por 1 · 7 articles in total, counted once each' + the exact overlap caveat; no refusal sentence. Hover in the tallest column (2026-09-21): low 'eng: 7 mentions · running total 7 · 2026-09-21', higher fra 12, deu 15, ita 21, top 'por: 3 mentions · running total 24'. FAIL: clicking the eng legend chip hides the eng band AND removes the eng chip from the legend (5 chips left), so it cannot be clicked again to restore; only switching to Counts and back to By language brought it back (see the P2 legend defect). The 7 is keyword-based (list says 160), as the notes predict."},
  {"id": "N7", "result": "pass", "locales": ["en"], "screenshot": S+"N-N7-concept-en.png",
   "observed": "Concept view: centre 'climate' (SVG title 'climate · 7'), arms eng 3 · fra 3 · deu 1 · spa 1 · ita 1 · por 1, 'assembly' off eng and 'rapport' off fra, lines centre->arm->word only. 'Not observed in this corpus: ara: مناخ · nld: klimaat · rus: климат'. Arm titles 'English — climate', 'Spanish — clima — the same word in ita, por' (ita/por likewise). Hover text comes from native SVG <title> tooltips, not the #oo-tip bubble. No label outside the SVG at default (centre label 33 px), at maximum text size (slider End = 180, label 59 px) or in ⛶. Observation: ⛶ 'Enlarge the mindmap' made labels SMALLER (33 -> 24 px) at 1440 (see the Enlarge defect)."},
  {"id": "N8", "result": "pass", "locales": ["en"], "screenshot": S+"N-N8-trends-hover-en.png",
   "observed": "'climate' already in Rising/Top at the 7-day window. Hover bubble ends '— Across languages: English 9 · French 7 · German 3 · Spanish 3'; reached by keyboard after 6 Tab presses from Window (days), same bubble. Non-concept row 'المناخ' has no 'Across languages'. Watch added ('Watch added…'); row reads 'This watch covers the concept “climate” in every language its ring carries.'; hovering the concept shows 'en: climate · fr: climat · de: klima · …'; the ring caveat appears once at the foot. (Bubble also carries an English-only caveat sentence in other locales, see N11.) Red ✕ never pressed."},
  {"id": "N9", "result": "pass", "locales": ["en"], "screenshot": S+"N-N9-reindex-en.png",
   "observed": "الإقليمية / الاقليميه / الإِقْلِيمِيَّة all 55, rows ara, no grey block; على 27 = علي 27; 预算 28 and 诊所 27, rows zho. Confirm text exact. Status 'Articles checked: 462 · re-indexed: 0 (Arabic: 0 · Chinese: 0 · Japanese: 0)'. Report tab (/api/search/index-job/report) JSON: articles_checked 462, articles_reindexed 0, by_script all 0 — matches."},
  {"id": "N10", "result": "pass", "locales": ["en"], "screenshot": S+"N-N10-bulletin-en.png",
   "observed": "Bulletin controls shown (gate hidden), Weekly -> 'Draft built.'; Review offers Narrate/Preview/Download report + annexes/Report only/Publish (only Download pressed). 'Downloaded: the report and 30 annexed article(s).' Two files: 20260926_OOS_Bulletin_Weekly.md and …_Annexes.zip (33 entries). 20260926_OOS_Bulletin_Weekly/CROSS-LANGUAGE-CONCEPTS.md present; first line '# Cross-language concepts in this edition', the hand-vetted Wikidata sentence, the overlap caveat, then '## climate' with Ring climate, Merged in rising_concepts, Forms present 4, Forms the ring defines 7 and the table en climate 9 · fr climat 7 · es clima 3 · de klima 3 (copy in downloads/). Edition deleted via its row (confirm 'Delete this edition? The corpus is untouched…'), list back to 'No editions yet'."},
  {"id": "N11", "result": "fail", "locales": ["fr", "ar", "zh", "ja", "en"], "screenshot": S+"N-race-ar-concept.png",
   "observed": "fr: palette 'Analyse: “climat”'; climat total 160 (= climate, R10 holds); literal total 3 ('climat 3'); block, links, both caveats, readout, sense picker, '40 formes comptées sur 44', 'Rechercher toutes les formes', 'Par langue' + caveat all French; 0 px overflow. ar: dir=rtl, sidebar on the right (x 1190-1440), block/caveats/readout/limit/stacked caveat/Concept ('المفهوم', 'لم تُرصد في هذه المجموعة')/Insights hover 'عبر جميع اللغات' Arabic, overflow 0. zh and ja: '语言/按语言分组/仅显示我输入的词' and '言語/言語でグループ化/入力した語だけを表示', same numbers as en (160/156/7/216/40 of 44). FAILS: (1) the stale-render race hit the ar and ja 'climate' tabs (showed election/public-election, 216, under “climate”) and the zh climate view kept election's language chips (P1 race defect); (2) the leaked sense pin: the climate tab URL carried sense=election%3Apublic-election and every 'Analysis: election' in ar/zh/ja opened already pinned to “public election” (216) instead of the sense picker (P2 sense-pin leak defect); (3) English left on translated pages: Insights hover sentence 'Counts only, never a score. The trend ratio is noisy…' (hover caveat defect); watch row '≥ 2 articles within 30 day(s) · last fired: never' and 'the concept “climate”' stay English after a language switch until reload (watch-list re-render defect); user's watch name 'Climate' shown as 'مناخ'/'Climat'/'气候'/'気候' (watch-name defect); Search page '160 result(s) (showing 50)' in fr (search-line defect); zh/ja ASCII '.' after the declined sentence (i18n slips defect). Watch deleted at the end (confirm 'Delete this watch and its history?', list empty)."},
  {"id": "N12", "result": "not-measurable-here", "locales": ["en"], "screenshot": S+"N-N4-literal-en.png",
   "observed": "No operator install/real corpus here. On the ENCRYPTED seeded store: (a) Articles 160, (b) 'in total' 160, (c) Search page 160 result(s), (d) Trend By language '7 articles in total', (e) Sentiment n=21/160; literal: (a) 156 = 'climate 156'; Sentiment n=21/156. So (a)=(b)=(c) and (e)=(a) hold on an encrypted store; (d) is keyword-based and smaller. The >900 case (Sentiment silently describing the top 900) cannot be produced on a 462-article store."},
  {"id": "N13", "result": "not-measurable-here", "locales": ["en"], "screenshot": S+"N-N13-reindex1-en.png",
   "observed": "Stand-in (not the reference corpus): encrypted store indexed by pre-S8 code, served by main, unlocked through the lock screen. BEFORE: 预算 0, 诊所 0, الإقليمية 55, الاقليميه 55, الإِقْلِيمِيَّة 0, على 27, علي 27, climate 160. Run: confirm exact; no 'not been upgraded' message; line 'Articles checked: 462 · re-indexed: 111 (Arabic: 56 · Chinese: 55 · Japanese: 0)', report JSON identical (n13-report1.json). AFTER: 预算 28, 诊所 28, الإِقْلِيمِيَّة 55, the others unchanged, climate 160 unchanged. Second run 're-indexed: 0'. The heh spelling already matched before the re-index here; the harakat spelling is the one that moved 0 -> 55. The job took 0.1 s, so the task manager's running row/progress bar/Pause could not be observed (no row after completion); interruption/continue not exercised; no Japanese articles."}
 ],
 "page_errors": [],
 "http_errors": [],
 "junk_text": [],
 "defects": [
  {"title": "A new analysis browser tab can paint another workspace tab's results under its own label (list, total, grey block, chips)", "severity": "P1", "step_ids": ["N5", "N11", "N13"],
   "repro": "Open 'Analysis: “climate”' from the palette (new browser tab), keep it; from the first tab open 'Analysis: “election”'. In the new tab the strip shows election active and the header “election”, but Articles shows climate's block, source/language chips and '160 Articles' with climate rows. Intermittent: final en run 1/1, probe 1/4, ar and ja climate tabs, the N13 预算 tab; zh kept only the other tab's chips.",
   "expected": "The Articles panel describes the active tab's query (election: declined-sense block, 20 articles, eng 20).",
   "actual": "The previously active workspace tab's run finishes last and overwrites the shared panels; clicking the tab in the strip again repaints it correctly.",
   "evidence": "shots/N-race-en-N5.png, N-race-ar-concept.png, N-race-ja-concept.png, N-race-probe-en.png; R-en-all.json 'races'; R-loc-fr-ar-zh-ja.json 'races'. Cause: src/static/app-boot.js:459 showTab('analyze') hydrates the restored active tab (src/static/app-shell.js:146-150 -> _anApplySeed -> loadAnalysis) and app-boot.js:475 openAnalysisFor then starts a second loadAnalysis; loadAnalysis (src/static/app-analysis.js:1961) has no stale-run guard and _anLoadArtFacets (:1289) writes one global."},
  {"title": "A sense pin leaks across analysis tabs: new tabs open pre-pinned and carry another tab's sense in their URL", "severity": "P2", "step_ids": ["N11", "N5"],
   "repro": "In fr, pick “public election” on an election analysis, then (other browser tabs) open 'Analysis: “climate”' and later 'Analysis: “election”' from the palette.",
   "expected": "A new analysis starts from the default lens: election shows the sense picker (20 articles); the climate URL has no sense=.",
   "actual": "Climate URL became ?analyze=climate&sense=election%3Apublic-election (still there after literal toggle and after re-clicking the tab); election in ar, zh and ja opened as 'searching the concept “public election”, which you chose' with 216 articles, skipping the picker.",
   "evidence": "R-loc-fr-ar-zh-ja.json: ar/zh/ja el_url0, el_sense_already_pinned=true, el_total0=216, literal_url; shots/N-race-ar-concept.png. Likely the same concurrent-hydration path as the P1 race (app-shell.js:146-150 + app-analysis.js:161-168 _anApplySeed/_anWriteLensToUrl)."},
  {"title": "ooChart legend: hiding a series removes its chip, so it cannot be clicked back", "severity": "P2", "step_ids": ["N6"],
   "repro": "Analysis climate -> Trend -> By language -> click the 'eng' legend chip, then try to click it again.",
   "expected": "The chip stays (aria-pressed=false, dimmed) and a second click restores the band.",
   "actual": "The eng band and its chip both disappear (5 chips left); only switching view to Counts and back restores it. Affects every ooChart chart.",
   "evidence": "shots/N-N6-legend-hidden-en.png; R-en-all.json N6.legend_after_hide / hidden_chip_still_present=false. src/static/app-markets.js:1968-1970 visible() filters hidden series and :2253 builds the legend from that list, so the opacity/aria-pressed=false branch is unreachable."},
  {"title": "Articles default order is relevance while 'Interleave by date' is shown pressed (Q508 = 'interleaved by date')", "severity": "P2", "step_ids": ["N2"],
   "repro": "Analysis climate -> Articles with 'Sort by: Relevance / recency'.",
   "expected": "Per Q508 the default list is interleaved by date, or the pressed control does not claim it.",
   "actual": "Published dates are not in date order (first rows 09-23, 09-22, 09-20, 09-24, 09-24, 09-25) while 'Interleave by date' has aria-pressed=true; only 'Sort by: Date' gives date order. Already known (sheet note 3).",
   "evidence": "R-en-all.json N2.default_first12 / interleave_pressed_by_default; shots/N-N2-articles-default-en.png; src/api/main.py:1458, src/database/fts.py:937."},
  {"title": "Watches list keeps English composite strings after a language switch until reload", "severity": "P3", "step_ids": ["N11", "N8"],
   "repro": "Insights -> Watches with a 'Climate' watch in en; switch to العربية (or fr/zh/ja) and open Watches again without reloading.",
   "expected": "'‏≥ 2 مقالات خلال 30 يوم · آخر تفعيل: أبدًا' and 'المفهوم «climate»' (keys exist in all four locales).",
   "actual": "'≥ 2 articles within 30 day(s) · last fired: never' and 'the concept “climate”' stay English in ar, fr, zh and ja; after a page reload they are translated.",
   "evidence": "R-ar-ins2.json vs R-ar-ins3.json; shots/N-N11-watch-ar-reload.png; src/static/app-insights.js:1269-1330 (loadWatches renders once with tf())."},
  {"title": "The user's watch name is machine-translated on screen", "severity": "P3", "step_ids": ["N11"],
   "repro": "Add a watch named 'Climate', then switch the UI to ar/fr/zh/ja.",
   "expected": "The name the user typed ('Climate') is shown as typed.",
   "actual": "Shown as 'مناخ', 'Climat', '气候', '気候' (the DOM translator matches the <b> text against the 'Climate' key).",
   "evidence": "R-ar-ins2.json, R-ar-ins3.json; src/static/app-insights.js:1305 (<b>${esc(w.name)}</b> is not marked no-translate); src/static/locales/ar.json:2125."},
  {"title": "Insights term-bar hover caveat is English in every locale", "severity": "P3", "step_ids": ["N11", "N8"],
   "repro": "Switch to العربية, Insights -> Trends, hover 'climate'.",
   "expected": "The whole bubble in Arabic.",
   "actual": "'…· Counts only, never a score. The trend ratio is noisy on a young corpus; co-occurrence and PMI are association, not causation. Deduced from your corpus, not a claim about the world. — عبر جميع اللغات: …' (no locale key exists for that sentence).",
   "evidence": "R-ar-ins3.json ins_hover_ar_after_reload; shots/N-N11-insights-hover-ar.png; src/analytics/queries.py:3052."},
  {"title": "Mindmap ⛶ 'Enlarge' makes the labels smaller on a wide window", "severity": "P3", "step_ids": ["N7"],
   "repro": "Analysis climate -> Mindmap -> Concept -> ⛶ at 1440x950.",
   "expected": "A larger picture.",
   "actual": "The rendered SVG keeps the same width and the centre label drops from 33 px to 24 px tall.",
   "evidence": "R-en-all.json N7.centre_label_px_default/enlarged; shots/N-N7-concept-en.png vs N-N7-concept-enlarged-en.png; src/static/app-analysis.js:1033-1034 (viewBox 680x460 -> 1100x720 while the svg is width=100%)."},
  {"title": "Insights -> Trends scrolls sideways at 375 px", "severity": "P3", "step_ids": ["N8"],
   "repro": "375x800, hamburger -> Insights -> Trends.",
   "expected": "scrollWidth - clientWidth = 0.",
   "actual": "178 px of horizontal scroll: the '.tb-val' spans ('22 mentions — new in this period, nothing prior to compare') do not wrap. Articles, Trend, Mindmap and the election block have 0 overflow at 375.",
   "evidence": "R-375.json insights_overflow=178; probe_ins375.py output; shots/N-375-insights-trends-en.png."},
  {"title": "Airplane coachmark covers the palette results at 375 px and the sidebar's Insights item in Arabic", "severity": "P3", "step_ids": ["N2", "N11"],
   "repro": "(a) 375x800, open the palette and type climate while the coach is showing; (b) switch to العربية at 1440 and click Insights in the sidebar.",
   "expected": "The row's entry points stay clickable.",
   "actual": "(a) The coach (z-index 360, palette 151) sits over the 'Analysis: “climate”' row; elementFromPoint at the row centre is #net-coach. (b) Coach at [1162,62,1432,198] over the Insights nav item [1200,159,1429,200]; its 'Not now' intercepts the click. Both clear after 'Not now'.",
   "evidence": "shots/N-375-palette-coach-climate.png, N-N11-coach-rtl-ar.png; R-375.json palette_coach_overlap; R-ar-ins.json; src/static/app-core.js:1017-1058 (_placeCoach)."},
  {"title": "Search page result line is not translated", "severity": "P3", "step_ids": ["N11", "N3"],
   "repro": "Français -> palette 'Lancer la recherche booléenne complète pour “climat”'.",
   "expected": "A French result line.",
   "actual": "'160 result(s) (showing 50)'. Already known (sheet note 7).",
   "evidence": "R-misc.json search_meta_fr; shots/N-N11-search-fr.png; src/static/app-analysis.js:2314."},
  {"title": "Concept map ignores 'Show only the words I typed'", "severity": "P3", "step_ids": ["N7", "N4"],
   "repro": "Analysis climate -> Articles -> 'Show only the words I typed' (156) -> Mindmap -> Concept.",
   "expected": "The view follows the lens (English only) or says it does not.",
   "actual": "Still draws eng/fra/deu/spa/ita/por arms. Already known (sheet note 8).",
   "evidence": "R-misc.json concept_texts_literal; shots/N-N7-concept-literal-en.png; src/static/app-analysis.js:2031-2034."},
  {"title": "Disclosure wording: ring caveat under a declined term, and a limit sentence with no numbers", "severity": "P3", "step_ids": ["N5"],
   "repro": "Analysis election -> Articles; pick “public election”.",
   "expected": "No 'matched the concept in every language' caveat when nothing was expanded; Q503 words the disclosure as 'expanded to 40 of N forms'.",
   "actual": "The caveat prints under 'so it was not expanded'; '40 of 44 forms counted' appears only after 'Count each form'. Already known (sheet notes 4 and 5).",
   "evidence": "R-en-all.json N5.xlang0 / xlang_pick / forms_capped; src/analytics/equivalence.py:833-918; src/static/app-analysis.js:1576-1627."},
  {"title": "Small i18n and grammar slips on this row's surfaces", "severity": "P3", "step_ids": ["N11", "N2", "N8"],
   "repro": "zh/ja: open 'election'; any locale: Group by language or hover a single-article row.",
   "expected": "Locale punctuation and singular forms.",
   "actual": "zh 'election 指代多个概念，因此未做扩展. 搜索其中之一' (ASCII '.' after the translated frame, same in ja); 'spa 1 articles' group heading and '1 articles' in the Insights bubble.",
   "evidence": "R-loc-fr-ar-zh-ja.json zh/ja el_xlang_after_clear; src/static/app-analysis.js:1598-1599 (literal '. ' after tf()); :1826 t('{n} articles')."}
 ],
 "not_measurable": [
  "N12: the operator's own encrypted install with a real corpus; the Sentiment >900 cap (the store has 462 articles).",
  "N13 on the reference/real corpus: measured on a pre-S8-indexed encrypted stand-in instead. The task manager's running row, progress bar, missing Pause/Resume and English label could not be seen because the job finished in 0.1 s; the interrupt/continue confirm was not exercised.",
  "Japanese search word splitting: no Japanese articles in the seed (sudachipy 0.7.0 is installed and the report says japanese:true).",
  "The watch firing path (needs new articles after the watch).",
  "Q515 timing at ring-size extremes, PF12 (sudachipy vs janome), Q506 packaging, Q503 'most frequent first' order, Q514 opt-in, Q516 (per the sheet's not_clickable list).",
  "Consent popup: no step in this row raised one, so there was nothing to screenshot or cancel."
 ],
 "summary": "The click-through clause does not close on this walk. The toggles, cap switch, sense picker, chips, per-form counts, stacked chart, concept map, watch disclosure, bulletin annexe and the Arabic/Chinese re-index all behave as ruled in en/fr/ar/zh/ja on an encrypted store; the stand-in re-index moved 预算 and 诊所 from 0 to 28 and the voweled Arabic spelling from 0 to 55, re-indexing 111 of 462 articles. It fails on a P1 race where a new analysis tab can show another tab's results under its own label, a P2 sense-pin leak across tabs, and a P2 stacked-chart legend chip that cannot be restored. The real-install parts (N12, N13) still need the operator's corpus."
}
json.dump(report, open("/tmp/claude-0/walk/N/report.json", "w"), ensure_ascii=False, indent=1)
print("ok", len(report["steps"]), len(report["defects"]))
