import json, sys
sys.path.insert(0, "/tmp/claude-0/walk/N")
from lib import *
from playwright.sync_api import sync_playwright

rec = Recorder("explore1")
with sync_playwright() as p:
    b = launch(p)
    ctx = b.new_context(viewport={"width": 1440, "height": 950})
    rec.attach_context(ctx, "x1")
    page = ctx.new_page()
    rec.attach(page, "main")
    print("unlocked:", unlock_if_locked(page))
    print("url", page.url)
    page.wait_for_timeout(2000)
    print("dialogs open:", page.evaluate("() => [...document.querySelectorAll('dialog[open]')].map(d=>d.id)"))
    shot(page, "x-home")
    close_dialogs(page)
    print("net-toggle:", page.evaluate("() => { const b=document.getElementById('net-toggle'); const p=b&&b.querySelector('[fill]'); return {title:b&&b.title, html:b&&b.innerHTML.slice(0,400)}; }"))
    open_palette_type(page, "climate")
    print("rows:", palette_rows(page))
    ap = open_analysis_new_tab(ctx, page, "climate")
    print("ap url", ap.url)
    select_subtab(ap, "articles")
    tot = wait_art_total(ap)
    print("total", tot)
    print("XLANG:", text(ap, "#an-xlang"))
    print("FACETS:", text(ap, "#an-art-facets"))
    print("TOTAL LINE:", text(ap, "#an-art-total"))
    print("HEADERS:", ap.eval_on_selector_all("#an-art-list table tr:first-child th", "e=>e.map(x=>x.innerText.trim())"))
    rows = ap.eval_on_selector_all("#an-art-list table tr[data-aid]", "rs=>rs.slice(0,12).map(r=>[...r.querySelectorAll('td')].map(td=>td.innerText.trim().slice(0,40)))")
    for r in rows: print(r)
    shot(ap, "x-articles-en")
    b.close()
rec.save()
print(json.dumps({"pe": rec.page_errors, "ce": rec.console_errors, "http": rec.http_errors}, indent=1, ensure_ascii=False))
