#!/usr/bin/env python3
"""
Build the city coordinate gazetteer (configs/cities.yml) from Wikidata.

Open Omniscience - Global Intelligence Platform for Investigative Journalism
Copyright (C) 2026 Ideotion. GPL-3.0-or-later.

Run on a machine WITH network. Queries Wikidata (CC0) for cities with coordinates
(P625), country (P17 -> ISO P297) and population (P1082), above a population
threshold, and writes configs/cities.yml — preferred over the shipped sample by
the Insights map. Pure parsing lives in src/catalog/cities.py (unit-tested).

Examples:
  python scripts/build_city_gazetteer.py                 # >= 100k population
  python scripts/build_city_gazetteer.py --min-pop 50000 --dry-run
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import yaml  # noqa: E402

from src.catalog.cities import parse_cities_sparql  # noqa: E402
from src.wiki.mediawiki import api_endpoint  # noqa: E402 (only for UA constant reuse)

WDQS = "https://query.wikidata.org/sparql"
_OUT = Path(__file__).resolve().parents[1] / "configs" / "cities.yml"
_UA = (
    "OpenOmniscienceBot/0.4 (+https://github.com/ideotion/Open-Omniscience; "
    "city gazetteer builder; contact open-omniscience@ideotion.com)"
)


def _query(min_pop: int) -> str:
    # Human settlements (city Q515 + subclasses) with coords, country, population.
    return f"""
SELECT ?cityLabel ?coord ?cc ?population WHERE {{
  ?city wdt:P31/wdt:P279* wd:Q515 ;
        wdt:P625 ?coord ;
        wdt:P1082 ?population .
  FILTER(?population >= {min_pop})
  OPTIONAL {{ ?city wdt:P17 ?country . ?country wdt:P297 ?cc . }}
  SERVICE wikibase:label {{ bd:serviceParam wikibase:language "en" . }}
}}
"""


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--min-pop", type=int, default=100000, help="minimum population (default 100000)"
    )
    ap.add_argument("--out", type=Path, default=_OUT)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    try:
        import requests
    except ImportError:
        print("needs `requests` (core dep).", file=sys.stderr)
        return 2

    _ = api_endpoint  # silence unused (kept for shared UA conventions)
    s = requests.Session()
    s.headers.update({"User-Agent": _UA, "Accept": "application/sparql-results+json"})
    print(f"Querying Wikidata for cities >= {args.min_pop} population…", file=sys.stderr)
    r = s.get(WDQS, params={"query": _query(args.min_pop), "format": "json"}, timeout=300)
    r.raise_for_status()
    cities = parse_cities_sparql(r.json())
    # Deduplicate by (name, country) keeping the most populous.
    best: dict[tuple, object] = {}
    for c in cities:
        k = (c.name.lower(), c.country)
        if k not in best or (c.population or 0) > (best[k].population or 0):
            best[k] = c
    rows = [c.to_dict() for c in best.values()]
    print(f"Parsed {len(rows)} cities.", file=sys.stderr)
    if args.dry_run:
        return 0
    args.out.write_text(
        "# Generated by scripts/build_city_gazetteer.py from Wikidata (CC0).\n\n"
        + yaml.safe_dump({"cities": rows}, allow_unicode=True, sort_keys=False, width=4096),
        "utf-8",
    )
    print(f"Wrote {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
