"""
Methods-appendix generator (0.0.9 WP1 / RM-07).

Open Omniscience - Global Intelligence Platform for Investigative Journalism
Copyright (C) 2026 Ideotion. GPL-3.0-or-later.

Emits the *how* behind an analysis as a Markdown document a fact-checker can
attach to a verdict and a researcher can hand to reviewers: the verbatim query,
the app version, generated-at, result counts, per-article provenance rows, and
a verification footer. It is a pure rendering over stored data — it computes
nothing new and concludes nothing; every number it prints is already in the
corpus or in the request.
"""

from __future__ import annotations

from datetime import UTC, datetime
from importlib.metadata import PackageNotFoundError, version

METHODS_SCHEMA = "oo-methods-1"


def _app_version() -> str:
    try:
        return version("open-omniscience")
    except PackageNotFoundError:  # pragma: no cover - source-tree edge
        return "unknown"


def build_methods_markdown(
    articles,
    *,
    query: str | None,
    case_name: str | None,
    notes: str | None,
    corpus_total: int,
    corpus_range: tuple[str | None, str | None],
) -> str:
    """Render the appendix. ``articles`` are ORM Article rows (already selected)."""
    now = datetime.now(UTC).isoformat(timespec="seconds")
    lines: list[str] = []
    lines.append(f"# Methods appendix — {case_name or 'untitled analysis'}")
    lines.append("")
    lines.append(f"*Generated by Open Omniscience v{_app_version()} on {now} "
                 f"(schema `{METHODS_SCHEMA}`).*")
    lines.append("")
    lines.append("## Selection")
    if query:
        lines.append(f"- **Query (verbatim, Boolean FTS):** `{query}`")
    else:
        lines.append(f"- **Selection:** {len(articles)} explicitly listed article id(s) "
                     f"(no query).")
    lines.append(f"- **Articles selected:** {len(articles)}")
    lines.append(f"- **Corpus at generation time:** {corpus_total} stored articles"
                 + (f", published {corpus_range[0]} → {corpus_range[1]}"
                    if corpus_range[0] else ""))
    if notes:
        lines.append(f"- **Analyst notes:** {notes}")
    lines.append("")
    lines.append("## Articles (provenance)")
    lines.append("")
    lines.append("| # | Title | Source | Published | URL | Content SHA-256 |")
    lines.append("|---|-------|--------|-----------|-----|-----------------|")
    for i, a in enumerate(sorted(articles, key=lambda x: x.id), 1):
        pub = a.published_at.date().isoformat() if a.published_at else ""
        src = getattr(a.source, "name", "") or ""
        title = (a.title or "(untitled)").replace("|", "\\|")
        lines.append(f"| {i} | {title} | {src} | {pub} | {a.url} | `{a.hash}` |")
    lines.append("")
    lines.append("## Verification")
    lines.append("")
    lines.append(
        "Each row's hash is the SHA-256 of the stored article body (whitespace-"
        "normalised). To verify integrity and provenance independently of this tool, "
        "request a signed evidence bundle for the same selection "
        "(`POST /api/reports/evidence`) and check it with "
        "`scripts/verify_evidence.py <bundle.json> [signer_public_key]` — verification "
        "needs only the bundle and the key, not this database."
    )
    lines.append("")
    lines.append(
        "*This appendix records selection and provenance only. It asserts no conclusion; "
        "analytical claims belong to the analyst, who can be checked against the rows "
        "above.*"
    )
    return "\n".join(lines)
