import json
W = "/tmp/claude-0/walk/I"
r = json.load(open(f"{W}/report_draft.json"))
r["defects"] = [
 {"title": "Stage-4 reading freezes when the run ends and reads 'could not be read' on every reopen, even while the re-index runs (Q204/Q205)", "severity": "P2", "step_ids": ["I7", "I9", "I8"],
  "repro": "Import four uncertified (pre-R24) backups at K = 3 with the dialog open and wait until the run ends. Then close and reopen Import…; also relaunch mid-drain, unlock, and open Import… while Processes shows the re-index running.",
  "expected": "Row 4 counts the re-index from the resume-status endpoint ('resuming re-index — X of Y' / 'N articles left to re-index'), and the third line reads 'Analytics are still catching up: …' until stage 4 is done, including after a reopen or a restart.",
  "actual": "At the end row 4 froze at '3,600 articles left to re-index' while the real backlog was 4,800 and draining (task manager 500 → 1000 / 4800). On every reopen, and after the restart while the drain was running, row 4 read 'could not be read' and the third line 'Whether analytics have caught up could not be read.', unchanged 4 s later.",
  "evidence": "I-I7-reopen-en.png, I-I9-import-after-restart-en.png, I-I8-taskmanager-en.png, events.jsonl (I7_all_done, I7_reopen_4s, I9_import_dialog_3s). src/static/app-backup.js:762 (reopen nulls _uxImRx), 1233-1251 (read only inside a running-queue tick; chain stops at terminal), 1697-1705 (_uxImReattach renders without reading)."},
 {"title": "'✓ Analytics are complete' and row 4 'complete' are shown at the START of an import, before anything is merged (Q203)", "severity": "P2", "step_ids": ["I4"],
  "repro": "On an install with no re-index backlog, start any corpus import and read the dialog in the first seconds.",
  "expected": "Q203: the analytics statement becomes true only after stage 4; it must not read ✓ complete while the import has not merged anything.",
  "actual": "Row 4 reads '4. Re-index the imported articles — complete' and the third line '✓ Analytics are complete — every imported article is indexed.' at 0/4 imported. Seen in both four-backup runs.",
  "evidence": "I-I4-running-en.png (and run1/I-I4-running-en.png); src/static/app-backup.js:1510-1529 (_uxImReindexBits: backlog 0 → 'complete'), 1553-1564 (_uxImStatements reads only the backlog)."},
 {"title": "Reopening the Import dialog is not a fresh page: the previous run's header, stage rows, statements and per-backup rows re-render under 'Last import' (R1/Q201)", "severity": "P2", "step_ids": ["I7", "I9", "I1"],
  "repro": "Finish any import, close the dialog (or restart the app), and reopen Settings → Data & backup → Import….",
  "expected": "One quiet line 'Last import · <date> · N articles · open report' and nothing else (index.html comment at #ux-imp-last; Q201 = a).",
  "actual": "Beneath the line: '4/4 imported · 14s', the four numbered stage rows, the three statements and four per-backup 'Done' rows. After a restart it also shows row 3 'not started', and after an interrupted run the red 'interrupted … start it again.' line.",
  "evidence": "I-I7-reopen-en.png, I-I9-import-after-restart-en.png, I-I13b-after-relaunch-en.png; src/static/app-backup.js:1697-1705 (_uxImReattach renders any saved run); POST /api/backup/import-queue/clear has no frontend caller."},
 {"title": "'✓ Safe to close or update the app' appears before the run is recorded finished; a stop during stage 3 boots into 'interrupted … start it again' (Q203)", "severity": "P2", "step_ids": ["I13"],
  "repro": "Import one backup. The moment its row reads Done while stage 3 (search-index merge) still runs, which is when both ✓ lines are due, stop the app (SIGKILL used here; stage 3 was sub-second). Relaunch, unlock, open Import….",
  "expected": "After '✓ Safe to close or update the app', closing costs nothing and nothing asks to redo the import; stages 3-4 resume on the next boot.",
  "actual": "Red 'This import was interrupted when the app stopped. It cannot resume (the passphrase is never stored) — start it again.' under '1/1 imported · 27s', and row 3 'Merge the search index — not started', although the backup's 1,200 articles were committed (history row 06:18 · restore · 1,200 articles). Stage 3 is not resumed. Only the re-index auto-resumed.",
  "evidence": "I-I13b-after-relaunch-en.png, events.jsonl (I13b_kill: items done, search_index running, live 'merging the search index after the import'; I13b_dialog_after_relaunch); src/static/app-backup.js:1533-1551 (✓ lines keyed on item state), src/backup/import_queue.py:634-647 (run saved done only after _tune_after_run), 345-352 (running → interrupted on boot)."},
 {"title": "The dialog's checkpoint sentence ignores the stored 'Backups per save point' until a run starts", "severity": "P2", "step_ids": ["I12"],
  "repro": "Settings → Data & backup → set 'Backups per save point' to 1 and tab out ('Preferences saved.'), then open Import….",
  "expected": "The sentence never disagrees with the K the next run will use: 'Every backup is verified and written to your corpus as soon as it finishes.'",
  "actual": "The sentence still reads 'Verified and written to your corpus once every 3 backups — …'. /api/settings import_checkpoint_k = 1 but /import-queue/status checkpoint.k = 3.",
  "evidence": "I-I12-k1-dialog-en.png, events.jsonl I12_k1; src/static/app-backup.js:830-843; src/backup/import_queue.py:303 (K initialised to 3), 537 (re-read only at run start), 1203."},
 {"title": "End-of-run result block over-counts the re-index backlog ('8,400 article(s) still to index' after a 4,800-article import)", "severity": "P2", "step_ids": ["I7"],
  "repro": "Import four distinct 1,200-article uncertified backups at K = 3 with the dialog open until the run ends.",
  "expected": "The indexing caveat states the real pending count (4,800, the drain's own total).",
  "actual": "'Indexing continues in the background: 8,400 article(s) still to index.' The block sums each committed item's whole-backlog snapshot (3,600 at the group save + 4,800 at backup 4).",
  "evidence": "events.jsonl I7_all_done (summary) vs I8_samples (total 4800); src/static/app-backup.js:2232-2241 (pend += r.articles_pending per item)."},
 {"title": "Held backups leave no persisted figures; history and the 'Last import' line show only per-report counts of a multi-backup run", "severity": "P2", "step_ids": ["I10", "I7"],
  "repro": "Import four distinct backups at K = 3, reopen the dialog, then open Settings → Data & backup → Import history.",
  "expected": "The persisted record, which R1 makes the only home of the detail, accounts for what each backup brought, and the Last import line says what the import added.",
  "actual": "Only two history rows (backups 3 and 4), each '1,200 articles'. Backup 3's row omits the 2,400 articles of backups 1–2 that its save committed, and 'Last import' reads '1,200 articles' for a 4,800-article import. With cumulative backups (run 1) it read '0 articles' for a run that grew the corpus by 933. The report also names no backup folder/path, and both reports are headed '(oo-backup-3)'.",
  "evidence": "I-I10-history-en.png, I-I10-report-en.png, run1/I-I7-reopen-en.png; src/backup/merge.py:6276-6292 vs 6700-6706 (report written only on the commit path)."},
 {"title": "Verify pressed during a running import hijacks the one poll chain and freezes the run's rows", "severity": "P3", "step_ids": ["I13"],
  "repro": "Start a single-backup import; while its row reads 'Running · … stage 1 of 4', press Verify once and watch for 30 s.",
  "expected": "Q206/R2: no competing messages, and the run's rows keep updating.",
  "actual": "POST /v2/volumes/verify 409. 'Verifying…' plus 'Verify: Merging (additive)… / Committing… · phase 11 of 18' then describe the import's own restore. The header and rows froze at '0/1 imported', 'Running · 0s · stage 1 of 4' for 30 s after the import had finished, and the result was 'No verification report was returned.'. Close/reopen restored the rows.",
  "evidence": "I-I13a-verify-pressed-en.png, I-I13a-after30s-en.png, i13a_samples.jsonl; src/static/app-backup.js:900-904 + 1137-1147 (409 'running' treated as a started verify), 1167-1178."},
 {"title": "Staged header line re-animates every second and overlaps the '0/4 imported' header (R2 blink)", "severity": "P3", "step_ids": ["I5", "I6"],
  "repro": "Import ≥ 2 backups at K = 3 and watch the dialog header while a backup reads 'Merged — not yet saved'.",
  "expected": "No blinking or overlapping status text (R2).",
  "actual": "The 'Merged, not yet saved: N — …' line is an inline <span class=\"note\">, whose .note rule gives it 11px padding, background, shadow and a 0.22 s slide-in animation. The header HTML includes the elapsed seconds, so it is rewritten each 1 s tick and the animation replays every second (animationstart at 6255 and 7271 ms). The box visibly covers the '0/4 imported · 7s' line.",
  "evidence": "I-I6-staged-en.png (crop-I6-header.png), events.jsonl I7_close_before_end/I7_toasts_run3 anims; src/static/app-backup.js:1383-1390 (stagedLine span.note) and 1417-1421 (note rewritten when HTML changes); src/static/app.css:1391-1393 (.note padding/shadow/animation)."},
 {"title": "Row 3 reads 'not started' after a restart although the search-index merge ran", "severity": "P3", "step_ids": ["I9"],
  "repro": "Finish an import, restart the app, unlock, open Import….",
  "expected": "Row 3 reads 'done' for a run that completed stage 3.",
  "actual": "'3. Merge the search index — not started' beside '4/4 imported' and two ✓ lines.",
  "evidence": "I-I9-import-after-restart-en.png; src/backup/import_queue.py:293, 305-312 (tuning_done not persisted), 1136-1144."},
 {"title": "Per-backup state words are untranslated (Done/Waiting/Skipped/Interrupted/Cancelled)", "severity": "P3", "step_ids": ["I11"],
  "repro": "Switch the UI to fr, ar or zh and open Import… after an import.",
  "expected": "Each backup's outcome is in the UI language.",
  "actual": "'… — Done · 4s · étape 2 sur 4' (fr), '… — Done · … المرحلة 2 من 4' (ar), '… — Done · … 第 2 步，共 4 步' (zh). None of the keys Done/Waiting/Skipped/Interrupted/Cancelled exist in en/fr/ar/zh.json ('Running' and 'Merged — not yet saved' do).",
  "evidence": "I-I11-dialog-fr.png, I-I11-dialog-ar.png, I-I11-dialog-zh.png; src/static/app-backup.js:1303-1316 (labels through t(variable)); src/static/locales/{fr,ar,zh}.json."},
 {"title": "Arabic (RTL): backup folder labels are bidi-scrambled in the per-backup rows", "severity": "P3", "step_ids": ["I11"],
  "repro": "Switch to العربية and open Import… with a run listed.",
  "expected": "Each row shows its folder name intact, e.g. '202609261808_OpenOmniscience_Backup_2'.",
  "actual": "Rendered as 'OpenOmniscience_Backup_2 — Done · 4s_202609261808': the digit prefix is detached and drawn after the state. The label is not direction-isolated.",
  "evidence": "I-I11-dialog-ar.png; src/static/app-backup.js:1446-1447 (label in <b> without dir=auto/bdi)."},
 {"title": "375 px: Import dialog's folder field collapses to ~40 px and backup labels are clipped", "severity": "P3", "step_ids": ["I-375"],
  "repro": "At 375 px wide open Settings → Data & backup → Import… after an import.",
  "expected": "No clipped text; the folder field usable.",
  "actual": "The page has no horizontal scroll (0). Inside the dialog, #ux-imp-src shows only '/m' beside Browse/Scan/Verify, and long backup labels overflow the dialog by 46 px, cut at its right edge.",
  "evidence": "I-375-dialog-en.png; events.jsonl W375 (dlgScroll 46)."},
 {"title": "A finished backup's row keeps '· stage 2 of 4'", "severity": "P3", "step_ids": ["I6", "I7"],
  "repro": "Any K = 3 import; read the per-backup rows after they turn Done.",
  "expected": "A Done row does not read as mid-way through the stages.",
  "actual": "'202609261808_OpenOmniscience_Backup_2 — Done · 4s · stage 2 of 4' for every finished backup.",
  "evidence": "I-I7-reopen-en.png; src/static/app-backup.js:1441-1444 (stage suffix rendered regardless of state)."},
 {"title": "First launch requests /api/system/data-location and gets 503 (outside row I)", "severity": "P3", "step_ids": ["I2"],
  "repro": "Boot a fresh data dir and accept the legal step on /unlock.",
  "expected": "The data-location probe answers during the fresh state, or is not requested.",
  "actual": "503 {\"locked\": true} on both throwaways. The path is not on ALLOWED_WHILE_LOCKED and app_is_locked() covers 'fresh', so the step falls through to the passphrase. Here OO_DATA_DIR was set, so skipping was correct, but the probe cannot succeed on any fresh install. To confirm in its own row.",
  "evidence": "events.jsonl http_error (8814 and 8815); src/api/unlock.py:76-92, src/api/main.py:751-762, src/static/unlock.html:344."}
]
r["summary"] = ("The click-through clause does NOT close on this walk. The four stage rows, the K = 3 group behaviour, the one bar, rows patched in place, reattach after reopen and reload, one toast, the task-manager drain and its boot auto-resume all worked on a real encrypted throwaway. But the dialog breaks rulings the clause names. "
 "Q203: '✓ Analytics are complete' at run start, and '✓ Safe to close' before the run is recorded finished, so a stop in stage 3 boots into 'interrupted … start it again'. Q204/Q205: stage 4 freezes, then reads 'could not be read' on every reopen and after a restart, never 'resuming re-index'. R1/Q201: reopen re-renders the whole previous run. Also untranslated per-backup states, a K sentence that ignores the setting, and an over-counted result block. "
 "Corpus-scale timing and the maintainer's real-install I1 remain not measurable here.")
json.dump(r, open(f"{W}/report.json", "w"), ensure_ascii=False, indent=1)
print(len(r["defects"]), "defects; report.json written")
