import json
W = "/tmp/claude-0/walk/I"
report = {
 "row": "I",
 "environment": {
  "encrypted": True,
  "seed": "Sources: scripts/ui_clickthrough_seed.py (default, 463 articles) + scratch seed_extra.py (distinct 160- and 1200-article batches through the real index_article chokepoint), all encrypted with OO_DB_PASSPHRASE. Backups made by the app's own export engine (the calls the Export dialog makes: /api/backup/export-folder -> /v2/volumes/start with verify_after_write -> /export-summary), one passphrase for all. Run 1 (throwaway tgt): 4 CUMULATIVE backups (463/623/783/943 articles) - on current main these carry R24-certified keywords, so no re-index backlog arose. Run 2 (throwaway tgt2): 4 DISTINCT backups of 1,200 articles each whose source index stamps were stripped (scratch strip_stamps.py, emulating pre-2026-09-24 backups) so stage 4 had a 4,800-article backlog; then backup5b (I13a) and backup6 (I13b) into the same throwaway. Run 3 (tgt3, port 8815): the 4 distinct backups again, for the reload/blink/toast checks. Every throwaway was created through the real first-launch flow (English, legal accepted, passphrase walk-pass-2026), so it was encrypted and every relaunch started LOCKED and was unlocked through #pw/#btn-unlock.",
  "ports": [8814, 8815],
  "scratch_dir": W,
  "notes": "Chromium (Playwright sync), 1440x950, en/fr/ar/zh + one 375 px en pass; app launched only with the open-omniscience console script, airplane mode kept (no consent popup arose: import/verify/scan/re-index make no network call). Each 4-backup run lasted about 12-14 s and stage 3 (search-index merge) was sub-second, so the dialog's 1 s poll never painted 'row 3 running'. I5's close/reopen x2 were done at 2 s intervals rather than 5 s, and the reload was done on a separate run (run 3), because a run ended before the planned sequence could complete. I13(b) used the step's harsher variant (SIGKILL fired by an API watcher the instant every backup read done while stage 3 ran), because the modal dialog plus the power button plus its confirm cannot land inside a sub-second stage 3. I1 needs the maintainer's REAL install and was not walked. Evidence: events.jsonl, run_samples.jsonl (run 2), run3_samples.jsonl, i13a_samples.jsonl, run1/ (run 1's events, samples and screenshots), the walk scripts walk1..walk6.py and the server logs tgt*.log. Every server I started was killed (the last two were PID 28267 on 8814 and PID 28535 on 8815)."
 },
 "steps": [
  {"id": "I1", "result": "not-measurable-here", "observed": "No real install exists in this sandbox, so neither the stored K on an old install nor its previous run's record could be read. The same surfaces were measured on the throwaway: K read 3 with the documented hint and hover bubble (I2). The dialog reopened after a run shows the 'Last import' line PLUS the previous run's header, four stage rows, three statements and per-backup rows. Row 4 then reads 'could not be read', and after a restart row 3 reads 'not started' (see I7/I9). On that evidence it is NOT a 'one line and nothing else' fresh page.", "screenshot": "I-I7-reopen-en.png"},
  {"id": "I2", "result": "pass", "observed": "Backups per save point = 3. Hint: 'Higher is faster and loses more work if an import is stopped or crashes.' The #oo-tip bubble begins '1 saves every backup to your corpus as soon as it finishes. Higher copies and checks your corpus once per group…'. Import history reads 'No imports recorded yet.' The Import dialog has an empty #ux-imp-last (no invented line), no stage or per-backup rows and 0 <details>, and shows 'Verified and written to your corpus once every 3 backups — nothing is durable until a save…'.", "screenshot": "run1/I-I2-dialog-en.png"},
  {"id": "I3", "result": "pass", "observed": "Verify on one backup folder with an empty passphrase: 'Verifying…', at most ONE visible progress bar (#ux-imp-bar) at any sample, with ONE progress line 'Verify: Verifying volumes…'. It ended '✓ Backup verified — the set is complete and intact.' / '3 volumes · signature: verified' / 'Parity: 1 · can still lose 1' / 'Method: …'. Scan on the parent: 'Restore corpus backup (encrypted volumes — additive, nothing you already have is overwritten · 15 volumes · 4 sets)', then 'What do you want to import?', the 'Passphrase (to decrypt the corpus backup)' field and the trust-history box appeared, and 'Import selected' was enabled.", "screenshot": "run1/I-I3-verified-en.png"},
  {"id": "I4", "result": "fail", "observed": "As expected: one bar; bold '0/4 imported · 1s' with 'Background collection is paused for this whole import and resumes when it finishes.'; four rows in order: '1. Check the backup and unpack it — 0 of 4 backups · Reassembling the archive…', '2. Merge it into your corpus and save — 0 of 4 backups', '3. Merge the search index — not started', '4. Re-index the imported articles — … open the task manager'. The two • lines were verbatim. Per-backup rows named by folder read '— Running · 1s · stage 1 of 4 · …' and '— Waiting'. Stop and 'Continue in background' were visible, with no 'Show details'. FAIL (Q203): at run start, before anything merged, row 4 read 'complete' and the third line read '✓ Analytics are complete — every imported article is indexed.' in BOTH runs.", "screenshot": "I-I4-running-en.png"},
  {"id": "I5", "result": "fail", "observed": "Passes: two close/reopen cycles during run 2 and one F5 reload during run 3 each found the SAME run (same four rows, not doubled, still counting). Never more than one visible <progress>. The drag selection anchored in the unchanged row 3 survived 10 s (anchor still connected, row 3 text still selected) while running rows were patched. A MutationObserver counted only 2 writes to row 3 over a whole run (initial + done). FAIL (R2 blink/overlap): while backups are staged, the header's 'Merged, not yet saved: N — …' line is an inline <span class=\"note\">. It is re-created on every 1 s tick (the header carries the elapsed seconds), so its .note slide-in animation replays every second (animationstart at 6255 ms and 7271 ms in a 2.5 s staged window), and its padded, shadowed box overlaps the '0/4 imported · 7s' line above it.", "screenshot": "I-I6-staged-en.png"},
  {"id": "I6", "result": "pass", "observed": "Run 2 (K = 3): backups 1 and 2 turned 'Merged — not yet saved' with a var(--warn) amber dot. The header gained 'Merged, not yet saved: 1 — written to your corpus at the next checkpoint, one every 3 backups.' (then 2) and stayed '0/4 imported'. Row 1 advanced (1 → 2 → 3 of 4) while row 2 stayed '0 of 4 backups'. When backup 3 finished, all three turned green 'Done' in the same sample, row 2 jumped to '3 of 4 backups' and the header to '3/4 imported'. At the same moment row 4 changed from 'complete' to '3,600 articles left to re-index' and the third line to 'Analytics are still catching up: 3,600 imported article(s) carry no keywords until the re-index finishes.' Backup 4 went straight to Done. No backup read Skipped. Run 1 showed the same group behaviour, but row 4 stayed 'complete' there because R24-certified backups create no backlog.", "screenshot": "I-I6-staged-en.png"},
  {"id": "I7", "result": "fail", "observed": "Passes: with all four Done the first two lines turned ✓ 'The import files can be removed — …' and ✓ 'Safe to close or update the app — …', and row 3 read 'done' (its 'running' state is sub-second and was never painted by the 1 s poll). With the dialog CLOSED before the end (run 3), exactly ONE toast 'Import complete.' appeared. With the dialog open at the end: the result block ('✓ Import successful', '4 of 4 backups imported · 14 s in total') and no toast. On reopen: no result block, and 'Last import · September 26, 2026 at 06:11 PM · 1,200 articles · open report' (backup 4's own report; run 1 showed '0 articles' for a 933-article run). FAIL (Q204): at the end row 4 froze at '3,600 articles left to re-index' while the real backlog was 4,800 and draining. On every reopen row 4 read 'could not be read' and the third line 'Whether analytics have caught up could not be read.', unchanged 4 s later. The reopened dialog also re-renders the whole previous run under the Last import line (R1). The result block said 'Indexing continues in the background: 8,400 article(s) still to index' for a 4,800-article import.", "screenshot": "I-I7-reopen-en.png"},
  {"id": "I8", "result": "pass", "observed": "The 'open the task manager' link in row 4 opened a new tab 'Task manager · FOOS' at /tasks. Processes → 'AI & ANALYSIS': 'running' pill, 'finishing the re-index of imported articles', detail 'import 1 (1200 article(s))', bar '500 / 4800 · 10.4%' → '900 / 4800 · 18.8%' → '1000 / 4800 · 20.8%'. Y = 4,800 did NOT match row 4's last reading of 3,600; that mismatch is the stage-4 freeze defect.", "screenshot": "I-I8-taskmanager-en.png"},
  {"id": "I9", "result": "fail", "observed": "Passes: the drain was at 1000/4800 (3,800 pending). Top-bar power → confirm 'Shut down the app? …' → the server exited. On relaunch the app came up LOCKED and was unlocked with the throwaway passphrase. With no click, Processes listed 'finishing the re-index of imported articles · import 2 (1200 article(s)) · 0 / 3600 · 0%' 8.1 s after unlock. Batch 1 had finished before exit, so 3,600 was exactly what remained. It counted to 3600/3600 (done, 0 failed). Omni search for 'Batch r elections 0' found 'Batch r elections 0 — en'. Import history still listed the reports. FAIL (Q205 in the dialog): opened while the resumed re-index was running, row 4 read 'could not be read' (never 'resuming re-index …'), the third line 'Whether analytics have caught up could not be read.', and row 3 '3. Merge the search index — not started' although it had run.", "screenshot": "I-I9-import-after-restart-en.png"},
  {"id": "I10", "result": "pass", "observed": "After Advanced → Data & backup, Import history listed newest first 'September 26, 2026 at 06:11 PM · restore · 1,200 articles · open report' and '… 06:10 PM · restore · 1,200 articles · open report', with no 'did not complete'. The top row matched the dialog's Last import line. 'open report' opened a new tab with plain Markdown '# Import report (oo-backup-3)' / '**1,200 new articles**' / per-table breakdown (English). As the code predicted, the four-backup run left only TWO rows (backups 3 and 4), and backup 3's row counts only its own 1,200 although its save committed 3,600 articles; backups 1–2 have no persisted figure. The report carries no backup folder/path line, and both reports are headed '(oo-backup-3)'.", "screenshot": "I-I10-history-en.png"},
  {"id": "I11", "locales": ["fr", "ar", "zh", "en"], "result": "fail", "observed": "Translated in each language: the Last import line ('Dernière importation · 26 septembre 2026 à 18:11 · 1,200 articles · ouvrir le rapport' / 'آخر استيراد · …' / '上次导入 · …'), the checkpoint sentence ('Vérifié et écrit dans votre corpus une fois toutes les 3 sauvegardes —…'), the four row titles, the three statements, 'Historique des imports' / 'سجل الاستيراد' / '导入历史', the K label, hint and hover bubble. In ar the dialog is direction rtl with the dots on the right. Back in English everything was English. FAIL: the per-backup state word 'Done' stayed English in fr, ar and zh. Per the locale files, 'Done', 'Waiting', 'Skipped', 'Interrupted' and 'Cancelled' have no key in any of en/fr/ar/zh. Also in ar the backup folder labels are bidi-scrambled ('OpenOmniscience_Backup_2 — Done · 4s_202609261808'). Known leftovers seen: raw 'restore' in history rows; numbers formatted '1,200' in fr (browser locale, not UI locale).", "screenshot": "I-I11-dialog-ar.png"},
  {"id": "I12", "result": "fail", "observed": "The override is visible and editable. 1 → Tab → 'Preferences saved.'; /api/settings import_checkpoint_k = 1, and the box read 1 after a reload. The Import dialog still said 'Verified and written to your corpus once every 3 backups — …' instead of 'Every backup is verified and written to your corpus as soon as it finishes.', because /import-queue/status reported checkpoint.k = 3. Undo: 3 → 'Preferences saved.', box reads 3, setting = 3.", "screenshot": "I-I12-k1-dialog-en.png"},
  {"id": "I13", "result": "fail", "observed": "(a) With a single-backup import in 'Running · 0s · stage 1 of 4', Verify was pressed once. POST /v2/volumes/verify returned 409, and Verify took over the dialog's one chain: status 'Verifying…', one bar, and a line 'Verify: Reassembling the archive… / Merging (additive)… / Committing… · phase 11 of 18' describing the IMPORT's own restore. The header, stage rows and backup row froze at '0/1 imported', '0 of 1 backups', 'Running · 0s · stage 1 of 4' for 30 s, although the import finished at about 6 s. It ended with 'No verification report was returned.'. Close/reopen restored the rows ('1/1 imported', row 3 'done'). There was never a second bar. (b) SIGKILL landed while the only backup read done and stage 3 ran (API: search_index running, live 'merging the search index after the import'), i.e. the state in which the dialog shows both ✓ lines. After relaunch + unlock the dialog showed '1/1 imported · 27s' plus the red 'This import was interrupted when the app stopped. It cannot resume (the passphrase is never stored) — start it again.', and row 3 read 'not started', although the backup's 1,200 articles were committed (history row 06:18 · 1,200 articles). The re-index auto-resumed (0/1200 running 5.5 s after unlock).", "screenshot": "I-I13b-after-relaunch-en.png"},
  {"id": "I-375", "locales": ["en"], "result": "fail", "observed": "At 375 px: document scrollWidth − clientWidth = 0 on Settings → Data & backup and with the Import dialog open (no page-level horizontal scroll). Inside the dialog, the 'Folder to import from' input is squeezed to about 40 px (shows '/m') beside Browse/Scan/Verify, and the long backup folder labels overflow the dialog by 46 px and are cut at its right edge.", "screenshot": "I-375-dialog-en.png"}
 ],
 "page_errors": [],
 "http_errors": [
  "GET /api/system/data-location -> 503 (first launch on 8814, twice, and on 8815; the lock gate answers 503 because the path is not on ALLOWED_WHILE_LOCKED)",
  "POST /api/backup/v2/volumes/verify -> 409 (I13a, Verify pressed during a running import; expected by the code, part of the I13a defect)",
  "net::ERR_CONNECTION_REFUSED console errors on the app and /tasks tabs right after the deliberate shutdown / SIGKILL (expected)"
 ],
 "junk_text": [],
 "defects": [],
 "not_measurable": [
  "I1 on the maintainer's REAL install: stored K on a pre-2026-09-16 settings file, and the real last run's record.",
  "Corpus-scale timings (gate 'Remaining', brief operator steps 1-2): here each backup took about 3-4 s and stage 3 was sub-second. 'Row 3 running' was never painted by the 1 s poll, so '✓ lines while row 3 still runs' is confirmed only from the API state plus the rendering code, not on screen.",
  "I13(b) with the UI power button: a sub-second stage 3 cannot be hit through the modal dialog + power button + confirm; SIGKILL was used instead.",
  "Closes (2) test half, Closes (3) route deletion, Q217, Q221, Q207 ruling: not clickable (as listed in the step plan)."
 ],
 "summary": ""
}
json.dump(report, open(f"{W}/report_draft.json", "w"), ensure_ascii=False, indent=1)
print("ok")
